/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/cake.glb -o src/pages/bday-cards/Cake.jsx 
Author: nodoxi (https://sketchfab.com/nodoxi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cake-fe318f681f7b48628ffc3fe153cbb08a
Title: Cake
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Cake(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/cake.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} scale={0.1}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="fd9e3d2cc2d94374818fff3c6b8927a1fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="bcake" />
                  <skinnedMesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.lambert1} skeleton={nodes.Object_6.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/cake.glb')
