/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/groot_dancing.glb 
Author: Сhemaron (https://sketchfab.com/chemaron)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/groot-dancing-5d7c5687bba747aa8a1ebeb3af514e34
Title: Groot dancing
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Groot(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/groot_dancing.glb");
  const { actions, mixer } = useAnimations(animations, group);

  useEffect(() => {
    actions["mixamo.com"].play();
    mixer.timeScale = 1;
  }, [actions, mixer]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.004}
        >
          <group name="Wave_Hip_Hop_Dancefbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="RetopoGroup1" />
                  <skinnedMesh
                    name="Object_6"
                    geometry={nodes.Object_6.geometry}
                    material={materials["Scene_-_Root"]}
                    skeleton={nodes.Object_6.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/groot_dancing.glb");
