/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/anatomy_girl.glb
Author: Riltariki (https://sketchfab.com/Riltariki)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/an-old-anatomy-girl-practice-dfba93f872b946a3b7c7d6f1b177f97e
Title: An old anatomy girl practice
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function AnatomyGirl(props) {
  const { nodes, materials } = useGLTF('/models/anatomy_girl.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={1}>
        <mesh geometry={nodes.Merged_Flowers1_Merged_Flowers1_0.geometry} material={materials.Merged_Flowers1} />
        <mesh geometry={nodes.Merged_Flowers1_Merged_Flowers1_0_1.geometry} material={materials.Merged_Flowers1} />
        <mesh geometry={nodes.Merged_Flowers1_Merged_Flowers1_0_2.geometry} material={materials.Merged_Flowers1} />
        <mesh geometry={nodes.Merged_Flowers1_Merged_Flowers1_0_3.geometry} material={materials.Merged_Flowers1} />
        <mesh geometry={nodes.Merged_Flowers1_Merged_Flowers1_0_4.geometry} material={materials.Merged_Flowers1} />
        <mesh geometry={nodes.Merged_Flowers1_Merged_Flowers1_0_5.geometry} material={materials.Merged_Flowers1} />
        <mesh geometry={nodes.Merged_Flowers1_Merged_Flowers1_0_6.geometry} material={materials.Merged_Flowers1} />
        <mesh geometry={nodes.Merged_Flowers1_Merged_Flowers1_0_7.geometry} material={materials.Merged_Flowers1} />
        <mesh geometry={nodes.Merged_Flowers1_Merged_Flowers1_0_8.geometry} material={materials.Merged_Flowers1} />
        <mesh geometry={nodes.Merged_Flowers1_Merged_Flowers1_0_9.geometry} material={materials.Merged_Flowers1} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/anatomy_girl.glb')
