/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/angel.glb
Author: sleepwalker77 (https://sketchfab.com/sleepwalker77)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/angel-99ef9c3b8f5649b0bc29e1ecfe0828bc
Title: Angel
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Angel(props) {
  const { nodes, materials } = useGLTF('/models/angel.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <mesh geometry={nodes['(null)_0'].geometry} material={materials['16_-_Defaultdd']} />
          <mesh geometry={nodes['(null)_1'].geometry} material={materials['1_-_Ddd']} />
          <mesh geometry={nodes['(null)_2'].geometry} material={materials['16_-_Default']} />
          <mesh geometry={nodes['(null)_2_1'].geometry} material={materials['16_-_Default']} />
          <mesh geometry={nodes['(null)_3'].geometry} material={materials['3_-_Default']} />
          <mesh geometry={nodes['(null)_3_1'].geometry} material={materials['3_-_Default']} />
          <mesh geometry={nodes['(null)_3_2'].geometry} material={materials['3_-_Default']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0}>
          <mesh geometry={nodes['(null)001_0'].geometry} material={materials['16_-_Defaultdd']} />
          <mesh geometry={nodes['(null)001_1'].geometry} material={materials['13_-_Default']} />
          <mesh geometry={nodes['(null)001_2'].geometry} material={materials['15_-_Default']} />
          <mesh geometry={nodes['(null)001_2_1'].geometry} material={materials['15_-_Default']} />
        </group>
        <mesh geometry={nodes.Sphere_0.geometry} material={materials['Material.001']} position={[-0.01, 0.23, 3.15]} scale={0.12} />
        <mesh geometry={nodes.Sphere001_0.geometry} material={materials['Material.001']} position={[-0.37, 0.44, 3.16]} scale={0.12} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/angel.glb')
