/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/girl_and_blob.glb
Author: Padalab (https://sketchfab.com/padalab)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/girl-and-blob-0606077a2305486eaf6af50a2fce5b43
Title: Girl And Blob
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { DissolveMaterial } from "../dissolve/DissolveMaterial";

export function GirlBlob(props) {
  const { nodes, materials } = useGLTF("/models/girl_and_blob.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry}>
        <DissolveMaterial baseMaterial={materials.Atlas} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
      </mesh>
      <mesh geometry={nodes.Object_6.geometry} material={materials.Atlas}>
        <DissolveMaterial baseMaterial={materials.Atlas} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
      </mesh>
      <mesh geometry={nodes.Object_7.geometry}>
        <DissolveMaterial baseMaterial={materials.outline} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
      </mesh>
      <mesh geometry={nodes.Object_9.geometry}>
        <DissolveMaterial baseMaterial={materials.Rays} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/girl_and_blob.glb");
