/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/godzilla_walk.glb
Author: carladoll996 (https://sketchfab.com/carladoll996)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/godzilla-first-walk-animationscrunchy32205-alt-e46c2cc5b698471588afd0ff9875d519
Title: Godzilla First Walk Animation(scrunchy32205 alt)
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { DissolveMaterial } from "../dissolve/DissolveMaterial";

export function Godzilla(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/godzilla_walk.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="c3ff413fcc8d4d158f1944d54b8294c6fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_161" position={[-2.58, -3.94, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={200} />
                    <skinnedMesh name="Object_162" geometry={nodes.Object_162.geometry} skeleton={nodes.Object_162.skeleton}>
                      <DissolveMaterial baseMaterial={materials["GZ_Body.001"]} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
                    </skinnedMesh>
                    <skinnedMesh name="Object_163" geometry={nodes.Object_163.geometry} skeleton={nodes.Object_163.skeleton}>
                      <DissolveMaterial baseMaterial={materials["GZ_ArmsLegs.001"]} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
                    </skinnedMesh>
                    <skinnedMesh name="Object_164" geometry={nodes.Object_164.geometry} skeleton={nodes.Object_164.skeleton}>
                      <DissolveMaterial baseMaterial={materials["GZ_Scales.001"]} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
                    </skinnedMesh>
                  </group>
                </group>
                <group name="Godzilla" position={[-2.58, -3.94, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={200} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/godzilla_walk.glb");
