/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/odin_npc_elf_female_2.glb
Author: enzohao (https://sketchfab.com/enzohao)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/odin-npc-elf-female-2-2f1de0bcbe814173b415d58fd1e04689
Title: ODIN_NPC_Elf_female_2
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { DissolveMaterial } from "../dissolve/DissolveMaterial";

export function Elf(props) {
  const { nodes, materials } = useGLTF("/models/odin_npc_elf_female_2.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.03}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh geometry={nodes.Object_6.geometry} skeleton={nodes.Object_6.skeleton}>
          <DissolveMaterial baseMaterial={materials.NPC_Elf_Female_02_mat_01} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
        </skinnedMesh>
        <skinnedMesh geometry={nodes.Object_8.geometry} skeleton={nodes.Object_8.skeleton}>
          <DissolveMaterial baseMaterial={materials.NPC_Elf_Female_02_HR_Low_mat} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
        </skinnedMesh>
        {/* <skinnedMesh geometry={nodes.Object_10.geometry} skeleton={nodes.Object_10.skeleton}>
          <DissolveMaterial baseMaterial={materials.NPC_Elf_Female_02_eyeshade_mat} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
        </skinnedMesh> */}
        <skinnedMesh geometry={nodes.Object_12.geometry} skeleton={nodes.Object_12.skeleton}>
          <DissolveMaterial baseMaterial={materials.NPC_Elf_Female_02_mat_02} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
        </skinnedMesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/odin_npc_elf_female_2.glb");
