/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/pan.glb
Author: TALOS (https://sketchfab.com/TALOS.)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pan-65c393f9e34444f7837a6f6f6f74b4cf
Title: Pan
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { DissolveMaterial } from "../dissolve/DissolveMaterial";

export function Pan(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/pan.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.06}>
          <group name="Female_Standing_Posefbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_7" />
                  <group name="Object_10" />
                  <group name="Object_12" />
                  <group name="Object1" />
                  <group name="TOK_000_Rist_EMDFBXMeshNode017" />
                  <group name="TOK_000_Pants_EMDFBXMeshNode016" />
                  <group name="TOK_000_Bust_EMDFBXMeshNode011" />
                  <group name="TOK_000_Boots_EMDFBXMeshNode010" />
                  <group name="40_Material63_1_0_0" />
                  <group name="PAN_000_Hair001_EMDFBXMeshNode022" />
                  <group name="PAN_000_Face_eye001_EMDFBXMeshNode021" />
                  <group name="PAN_000_Face_base001_EMDFBXMeshNode020" />
                  <skinnedMesh name="Object_6" geometry={nodes.Object_6.geometry} skeleton={nodes.Object_6.skeleton}>
                    <DissolveMaterial baseMaterial={materials["Scene_-_Root"]} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
                  </skinnedMesh>
                  <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} skeleton={nodes.Object_8.skeleton}>
                    <DissolveMaterial baseMaterial={materials["Scene_-_Root"]} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
                  </skinnedMesh>
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} skeleton={nodes.Object_9.skeleton}>
                    {" "}
                    <DissolveMaterial baseMaterial={materials["Scene_-_Root"]} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
                  </skinnedMesh>
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} skeleton={nodes.Object_11.skeleton}>
                    {" "}
                    <DissolveMaterial baseMaterial={materials["Scene_-_Root"]} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
                  </skinnedMesh>
                  <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} skeleton={nodes.Object_13.skeleton}>
                    {" "}
                    <DissolveMaterial baseMaterial={materials["Scene_-_Root"]} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
                  </skinnedMesh>
                  <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} skeleton={nodes.Object_14.skeleton}>
                    {" "}
                    <DissolveMaterial baseMaterial={materials["Scene_-_Root"]} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
                  </skinnedMesh>
                  <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} skeleton={nodes.Object_15.skeleton}>
                    {" "}
                    <DissolveMaterial baseMaterial={materials["Scene_-_Root"]} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
                  </skinnedMesh>
                  <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} skeleton={nodes.Object_16.skeleton}>
                    {" "}
                    <DissolveMaterial baseMaterial={materials["Scene_-_Root"]} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
                  </skinnedMesh>
                  <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} skeleton={nodes.Object_17.skeleton}>
                    {" "}
                    <DissolveMaterial baseMaterial={materials["Scene_-_Root"]} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
                  </skinnedMesh>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/pan.glb");
