/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/witch_daphne.glb
Author: Shortskirts (https://sketchfab.com/Shortestskirts)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gluttony-witch-daphne-b28e0d869f9149eba621c551d7733260
Title: Gluttony Witch ~ Daphne
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { DissolveMaterial } from "../dissolve/DissolveMaterial";

export function Witch(props) {
  const { nodes, materials } = useGLTF("/models/witch_daphne.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 1.6, 0, 0]} scale={1}>
            <primitive object={nodes._rootJoint} />

            {/* <mesh geometry={nodes.Plane005_Dress001_0.geometry} material={materials['Dress.001']} position={[-0.25, 0, 5.21]} scale={4.16} /> */}
            <mesh geometry={nodes.face_Skin_0.geometry} position={[-0.25, 0, 5.21]} scale={4.16}>
              <DissolveMaterial baseMaterial={materials.Skin} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
            </mesh>
            <mesh geometry={nodes.Blindfold_blindfold1_0.geometry} material={materials.blindfold1} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.blindfold_blindfold2_0.geometry} material={materials.blindfold2} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.Ears_Skin_0.geometry} material={materials.Skin} position={[-0.25, 0, 5.21]} scale={4.16} />
            <mesh geometry={nodes.hair001_Hair_0.geometry} material={materials.Hair} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.Plane_Dress_0.geometry} material={materials.Dress} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.Sphere_Dress_0.geometry} material={materials.Dress} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.Sphere001_Dress_0.geometry} material={materials.Dress} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.Circle_DarkMetal002_0.geometry} material={materials["DarkMetal.002"]} position={[-0.25, -0.27, 0]} />

            <mesh geometry={nodes.Plane022_Purple_Metal_0.geometry} material={materials.Purple_Metal} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.Torus_Dress_0.geometry} material={materials.Dress} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.Cylinder005_DarkMetal001_0.geometry} material={materials["DarkMetal.001"]} position={[-0.3, 8.04, 0]} scale={[1.05, 1, 1]} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/witch_daphne.glb");
