/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/witch_daphne.glb
Author: Shortskirts (https://sketchfab.com/Shortestskirts)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gluttony-witch-daphne-b28e0d869f9149eba621c551d7733260
Title: Gluttony Witch ~ Daphne
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Witch(props) {
  const { nodes, materials } = useGLTF('/models/witch_daphne.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
            <primitive object={nodes._rootJoint} />
            <group position={[-3.71, -1.05, -16.66]} rotation={[-0.05, 0.48, 0.09]}>
              <mesh geometry={nodes.leg1_Purple_Metal_0.geometry} material={materials.Purple_Metal} />
              <mesh geometry={nodes.leg1_DarkMetal_0.geometry} material={materials.DarkMetal} />
            </group>
            <group position={[3.08, -1.31, -16.71]} rotation={[-0.17, -0.41, -3.14]} scale={[-1, 1, 1]}>
              <mesh geometry={nodes.leg1001_Purple_Metal_0.geometry} material={materials.Purple_Metal} />
              <mesh geometry={nodes.leg1001_DarkMetal_0.geometry} material={materials.DarkMetal} />
            </group>
            <group position={[-3.12, 1.41, -16.76]} rotation={[0.15, 0.3, 0.03]}>
              <mesh geometry={nodes.leg1002_Purple_Metal_0.geometry} material={materials.Purple_Metal} />
              <mesh geometry={nodes.leg1002_DarkMetal_0.geometry} material={materials.DarkMetal} />
            </group>
            <group position={[2.85, 0.86, -16.67]} rotation={[0.19, -0.46, -3.04]} scale={[-1, 1, 1]}>
              <mesh geometry={nodes.leg1003_Purple_Metal_0.geometry} material={materials.Purple_Metal} />
              <mesh geometry={nodes.leg1003_DarkMetal_0.geometry} material={materials.DarkMetal} />
            </group>
            <group position={[1.26, 2.41, -16.77]} rotation={[0.32, -0.23, -3.07]} scale={[-1, 1, 1]}>
              <mesh geometry={nodes.leg1004_Purple_Metal_0.geometry} material={materials.Purple_Metal} />
              <mesh geometry={nodes.leg1004_DarkMetal_0.geometry} material={materials.DarkMetal} />
            </group>
            <group position={[-1.15, 2.46, -16.82]} rotation={[0.35, 0.1, -3.09]} scale={[-1, 1, 1]}>
              <mesh geometry={nodes.leg1005_Purple_Metal_0.geometry} material={materials.Purple_Metal} />
              <mesh geometry={nodes.leg1005_DarkMetal_0.geometry} material={materials.DarkMetal} />
            </group>
            <group position={[1.64, -3.34, -16.73]} rotation={[-0.17, -0.41, -3.14]} scale={[-1, 1, 1]}>
              <mesh geometry={nodes.leg1006_Purple_Metal_0.geometry} material={materials.Purple_Metal} />
              <mesh geometry={nodes.leg1006_DarkMetal_0.geometry} material={materials.DarkMetal} />
            </group>
            <group position={[-2.64, -3.01, -16.66]} rotation={[-0.2, 0.31, 2.32]} scale={[-1, 1, 1]}>
              <mesh geometry={nodes.leg1007_Purple_Metal_0.geometry} material={materials.Purple_Metal} />
              <mesh geometry={nodes.leg1007_DarkMetal_0.geometry} material={materials.DarkMetal} />
            </group>
            <mesh geometry={nodes.Plane005_Dress001_0.geometry} material={materials['Dress.001']} position={[-0.25, 0, 5.21]} scale={4.16} />
            <mesh geometry={nodes.face_Skin_0.geometry} material={materials.Skin} position={[-0.25, 0, 5.21]} scale={4.16} />
            <mesh geometry={nodes.Blindfold_blindfold1_0.geometry} material={materials.blindfold1} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.blindfold_blindfold2_0.geometry} material={materials.blindfold2} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.Ears_Skin_0.geometry} material={materials.Skin} position={[-0.25, 0, 5.21]} scale={4.16} />
            <mesh geometry={nodes.hair001_Hair_0.geometry} material={materials.Hair} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.Plane_Dress_0.geometry} material={materials.Dress} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.Sphere_Dress_0.geometry} material={materials.Dress} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.Sphere001_Dress_0.geometry} material={materials.Dress} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.Circle_DarkMetal002_0.geometry} material={materials['DarkMetal.002']} position={[-0.25, -0.27, 0]} />
            <mesh geometry={nodes.Circle001_DarkMetal002_0.geometry} material={materials['DarkMetal.002']} position={[-0.25, -0.58, 0]} />
            <mesh geometry={nodes.Cylinder_DarkMetal_0.geometry} material={materials.DarkMetal} position={[-0.3, 8.04, 0]} scale={[1.05, 1, 1]} />
            <mesh geometry={nodes.Cylinder001_DarkMetal_0.geometry} material={materials.DarkMetal} position={[4.92, -0.74, 0.16]} rotation={[0, 0, 0.91]} scale={[1, 1.05, 1]} />
            <mesh geometry={nodes.Cylinder002_DarkMetal_0.geometry} material={materials.DarkMetal} position={[-5.42, -0.83, 0.2]} rotation={[0, 0, -0.92]} scale={[1.01, 1.04, 1]} />
            <mesh geometry={nodes.Cylinder003_DarkMetal_0.geometry} material={materials.DarkMetal} position={[-4.26, -0.71, 4.97]} rotation={[0, 0, -1.45]} scale={[1.03, 1.02, 1]} />
            <mesh geometry={nodes.Cylinder004_DarkMetal_0.geometry} material={materials.DarkMetal} position={[3.61, -0.71, 4.97]} rotation={[0, 0, 1.53]} scale={[1.01, 1.03, 1]} />
            <mesh geometry={nodes.leg2_DarkMetal_0.geometry} material={materials.DarkMetal} position={[-3.71, -1.05, -16.66]} rotation={[-0.15, 0.34, 0.08]} />
            <mesh geometry={nodes.leg3_DarkMetal_0.geometry} material={materials.DarkMetal} position={[-3.71, -1.05, -16.66]} rotation={[-0.15, 0.34, 0.08]} />
            <mesh geometry={nodes.leg2001_DarkMetal_0.geometry} material={materials.DarkMetal} position={[2.84, -1.31, -16.71]} rotation={[-0.17, -0.41, 0]} scale={[-1, 1, 1]} />
            <mesh geometry={nodes.leg3002_DarkMetal_0.geometry} material={materials.DarkMetal} position={[2.84, -1.31, -16.71]} rotation={[-0.17, -0.41, 0]} scale={[-1, 1, 1]} />
            <mesh geometry={nodes.leg2002_DarkMetal_0.geometry} material={materials.DarkMetal} position={[-3.12, 1.41, -16.69]} rotation={[0.15, 0.3, 0.03]} />
            <mesh geometry={nodes.leg3001_DarkMetal_0.geometry} material={materials.DarkMetal} position={[-3.12, 1.41, -16.69]} rotation={[0.15, 0.3, 0.03]} />
            <mesh geometry={nodes.leg2003_DarkMetal_0.geometry} material={materials.DarkMetal} position={[2.84, 0.85, -16.63]} rotation={[0.19, -0.46, 0.1]} scale={[-1, 1, 1]} />
            <mesh geometry={nodes.leg3003_DarkMetal_0.geometry} material={materials.DarkMetal} position={[2.84, 0.85, -16.63]} rotation={[0.19, -0.46, 0.1]} scale={[-1, 1, 1]} />
            <mesh geometry={nodes.leg2004_DarkMetal_0.geometry} material={materials.DarkMetal} position={[1.26, 2.41, -16.77]} rotation={[0.33, -0.26, 0.08]} scale={[-1, 1, 1]} />
            <mesh geometry={nodes.leg3004_DarkMetal_0.geometry} material={materials.DarkMetal} position={[1.26, 2.41, -16.77]} rotation={[0.33, -0.26, 0.08]} scale={[-1, 1, 1]} />
            <mesh geometry={nodes.leg2005_DarkMetal_0.geometry} material={materials.DarkMetal} position={[-1.09, 2.43, -16.72]} rotation={[0.35, 0.1, 0.05]} scale={[-1, 1, 1]} />
            <mesh geometry={nodes.leg3005_DarkMetal_0.geometry} material={materials.DarkMetal} position={[-1.09, 2.43, -16.72]} rotation={[0.35, 0.1, 0.05]} scale={[-1, 1, 1]} />
            <mesh geometry={nodes.leg2006_DarkMetal_0.geometry} material={materials.DarkMetal} position={[1.64, -3.34, -16.73]} rotation={[-0.17, -0.41, 0]} scale={[-1, 1, 1]} />
            <mesh geometry={nodes.leg3006_DarkMetal_0.geometry} material={materials.DarkMetal} position={[1.64, -3.34, -16.73]} rotation={[-0.17, -0.41, 0]} scale={[-1, 1, 1]} />
            <mesh geometry={nodes.leg2007_DarkMetal_0.geometry} material={materials.DarkMetal} position={[-2.64, -3.01, -16.66]} rotation={[-0.2, 0.31, -0.82]} scale={[-1, 1, 1]} />
            <mesh geometry={nodes.leg3007_DarkMetal_0.geometry} material={materials.DarkMetal} position={[-2.64, -3.01, -16.66]} rotation={[-0.2, 0.31, -0.82]} scale={[-1, 1, 1]} />
            <mesh geometry={nodes.Plane006_DarkMetal_0.geometry} material={materials.DarkMetal} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.NurbsPath003_Purple_Metal_0.geometry} material={materials.Purple_Metal} />
            <mesh geometry={nodes.Plane007_DarkMetal_0.geometry} material={materials.DarkMetal} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.NurbsPath004_Purple_Metal_0.geometry} material={materials.Purple_Metal} />
            <mesh geometry={nodes.Plane008_DarkMetal_0.geometry} material={materials.DarkMetal} />
            <mesh geometry={nodes.NurbsPath005_Purple_Metal_0.geometry} material={materials.Purple_Metal} />
            <mesh geometry={nodes.Plane009_DarkMetal_0.geometry} material={materials.DarkMetal} />
            <mesh geometry={nodes.NurbsPath006_Purple_Metal_0.geometry} material={materials.Purple_Metal} />
            <mesh geometry={nodes.Plane010_DarkMetal_0.geometry} material={materials.DarkMetal} />
            <mesh geometry={nodes.NurbsPath007_Purple_Metal_0.geometry} material={materials.Purple_Metal} />
            <mesh geometry={nodes.Plane011_DarkMetal_0.geometry} material={materials.DarkMetal} />
            <mesh geometry={nodes.NurbsPath008_Purple_Metal_0.geometry} material={materials.Purple_Metal} />
            <mesh geometry={nodes.Plane012_DarkMetal_0.geometry} material={materials.DarkMetal} />
            <mesh geometry={nodes.NurbsPath009_Purple_Metal_0.geometry} material={materials.Purple_Metal} />
            <mesh geometry={nodes.Plane013_DarkMetal_0.geometry} material={materials.DarkMetal} />
            <mesh geometry={nodes.NurbsPath010_Purple_Metal_0.geometry} material={materials.Purple_Metal} />
            <mesh geometry={nodes.Plane018_Purple_Metal_0.geometry} material={materials.Purple_Metal} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.Plane022_Purple_Metal_0.geometry} material={materials.Purple_Metal} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.Torus_Dress_0.geometry} material={materials.Dress} position={[-0.25, 0, 0]} />
            <mesh geometry={nodes.Cylinder005_DarkMetal001_0.geometry} material={materials['DarkMetal.001']} position={[-0.3, 8.04, 0]} scale={[1.05, 1, 1]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/witch_daphne.glb')
