/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/xuxa.glb
Author: Xuxa-3D (https://sketchfab.com/xuxa2023)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/xuxa-paquita-azul-3d-8d6fbe2e77de4e789d0b139afdc80a6a
Title: Xuxa Paquita azul-3D
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Xuxa(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/xuxa.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature001_86">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="EyeLeft001_67" />
                  <group name="EyeRight001_68" />
                  <group name="Wolf3D_Body001_69">
                    <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['Wolf3D_Body.002']} />
                  </group>
                  <group name="Wolf3D_Body002_70" />
                  <group name="Wolf3D_Body003_71">
                    <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials['Materiais.015']} />
                  </group>
                  <group name="Wolf3D_Body004_72" />
                  <group name="Wolf3D_Body005_73">
                    <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials['Materiais.018']} />
                  </group>
                  <group name="Wolf3D_Body006_74" />
                  <group name="Wolf3D_Body007_75" />
                  <group name="Wolf3D_Body008_76">
                    <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials['Materiais.015']} />
                  </group>
                  <group name="Wolf3D_Body009_77">
                    <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials['Materiais.017']} />
                  </group>
                  <group name="Wolf3D_Body010_78" />
                  <group name="Wolf3D_Body011_79" />
                  <group name="Wolf3D_Body012_80">
                    <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials['Materiais.016']} />
                  </group>
                  <group name="Wolf3D_Body013_81" />
                  <group name="Wolf3D_Body014_82" />
                  <group name="Wolf3D_Head001_83" />
                  <group name="Wolf3D_Head002_84" />
                  <group name="Wolf3D_Teeth001_85" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['Wolf3D_Eye.002']} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Wolf3D_Eye.002']} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['Wolf3D_Body.001']} skeleton={nodes.Object_13.skeleton} />
                  <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials['Materiais.002']} skeleton={nodes.Object_17.skeleton} />
                  <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials['Materiais.008']} skeleton={nodes.Object_21.skeleton} />
                  <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials['Materiais.011']} skeleton={nodes.Object_23.skeleton} />
                  <skinnedMesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Materiais} skeleton={nodes.Object_29.skeleton} />
                  <skinnedMesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials['Materiais.005']} skeleton={nodes.Object_31.skeleton} />
                  <skinnedMesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials['Materiais.004']} skeleton={nodes.Object_35.skeleton} />
                  <skinnedMesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials['Materiais.023']} skeleton={nodes.Object_37.skeleton} />
                  <skinnedMesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials['Wolf3D_Skin.002']} skeleton={nodes.Object_39.skeleton} />
                  <skinnedMesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials['Materiais.012']} skeleton={nodes.Object_41.skeleton} />
                  <skinnedMesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials['Wolf3D_Teeth.002']} skeleton={nodes.Object_43.skeleton} />
                </group>
              </group>
              <group name="Plano_87" position={[0, 1.16, 0.08]} rotation={[-1.57, 0, 0]} scale={0.04}>
                <mesh name="mesh_19" geometry={nodes.mesh_19.geometry} material={materials['Materiais.013']} morphTargetDictionary={nodes.mesh_19.morphTargetDictionary} morphTargetInfluences={nodes.mesh_19.morphTargetInfluences} />
              </group>
              <group name="C��rculo_88" position={[-0.28, 1.02, 0.04]} rotation={[-0.08, 0.03, -0.33]} scale={0.11}>
                <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials['Materiais.003']} />
              </group>
              <group name="Cubo007_89" position={[0, 1.43, 0.04]} rotation={[-2.98, 1.49, 1.05]} scale={[0.04, 0.01, 0.03]}>
                <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials['Materiais.007']} />
              </group>
              <group name="Cubo008_90" position={[0.11, 1.49, -0.01]} rotation={[Math.PI, -0.13, -3]} scale={[0.04, 0.01, 0.03]}>
                <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials['Materiais.006']} />
              </group>
              <group name="Cubo010_91" position={[0.11, 1.49, -0.01]} rotation={[Math.PI, -0.13, -3]} scale={[0.04, 0.01, 0.03]}>
                <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials['Materiais.007']} />
              </group>
              <group name="C��rculo012_92" position={[0.08, 1.27, 0.13]} rotation={[-1.46, 0.15, 0.63]} scale={0.02}>
                <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials['Materiais.014']} />
              </group>
              <group name="B��zier_-_C��rculo002_93" position={[-0.38, 1.05, 0.01]} rotation={[-2.82, -0.8, 2.25]} scale={0.01}>
                <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials['Materiais.009']} />
              </group>
              <group name="C��rculo002_94" position={[-0.28, 1.02, 0.04]} rotation={[-0.08, 0.03, -0.33]} scale={0.11}>
                <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials['Materiais.001']} />
              </group>
              <group name="Nurbs_-_Guia_de_caminho_95" position={[0.01, 1.35, 0.1]} scale={0.21}>
                <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials['Materiais.022']} />
              </group>
              <group name="C��rculo001_96" position={[-0.33, 1.16, 0.09]} rotation={[-0.32, -0.88, -0.01]} scale={0.02}>
                <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials['Materiais.014']} />
                <mesh name="Object_131" geometry={nodes.Object_131.geometry} material={materials['Materiais.010']} />
              </group>
              <group name="C��rculo003_97" position={[0.08, 1.27, 0.13]} rotation={[-1.46, 0.15, 0.63]} scale={0.02}>
                <mesh name="Object_133" geometry={nodes.Object_133.geometry} material={materials['Materiais.010']} />
              </group>
              <group name="Nurbs_-_Guia_de_caminho001_98" position={[-0.25, 1.1, 0.14]} rotation={[0, 0, -0.34]} scale={0.13}>
                <mesh name="Object_135" geometry={nodes.Object_135.geometry} material={materials['Materiais.024']} />
              </group>
              <group name="Hair_16_99" position={[0, 1.53, 0.05]} scale={0.011}>
                <mesh name="Object_137" geometry={nodes.Object_137.geometry} material={materials['Materiais.020']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/xuxa.glb')
