/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/great_white_shark.glb
Author: BlueMesh (https://sketchfab.com/VapTor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/great-white-shark-b67415aaa0bd450d865f9604dcdac244
Title: Great White Shark
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function GreatWhite(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/great_white_shark.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.15}>
          <group name="Root">
            <group name="Hemi" position={[0.09, -1.28, 6.6]}>
              <group name="Hemi_1" />
            </group>
            <group name="Hemi001" position={[0.09, -0.58, -3.63]} rotation={[3.06, 0, 0]}>
              <group name="Hemi001_1" />
            </group>
            <group name="Armature" position={[0, -2.23, 0.06]}>
              <primitive object={nodes.Armature_rootJoint} />
              <group name="Plane" position={[0, 1.32, 0.16]} rotation={[-0.05, Math.PI / 2, 0]} scale={[1, 1, 2.59]} />
              <group name="Circle" position={[0.44, -1.97, 0.15]} rotation={[0, Math.PI / 2, 0]} scale={0.06} />
              <group name="Plane009" position={[0, -1.86, -0.15]} rotation={[-1.27, 0, -1.65]} scale={0.04} />
              <group name="Plane008" position={[0, -1.87, -0.24]} rotation={[2.01, 0, -1.65]} scale={0.02} />
              <skinnedMesh name="Plane_0" geometry={nodes.Plane_0.geometry} material={materials['Material.001']} skeleton={nodes.Plane_0.skeleton} />
              <skinnedMesh name="Circle_0" geometry={nodes.Circle_0.geometry} material={materials['Material.001']} skeleton={nodes.Circle_0.skeleton} />
              <skinnedMesh name="Plane009_0" geometry={nodes.Plane009_0.geometry} material={materials['Material.001']} skeleton={nodes.Plane009_0.skeleton} />
              <skinnedMesh name="Plane008_0" geometry={nodes.Plane008_0.geometry} material={materials['Material.001']} skeleton={nodes.Plane008_0.skeleton} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/great_white_shark.glb')
