/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/marie.glb
Author: w849138207 (https://sketchfab.com/w849138207)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/marie-f90a4564a6d24268aad19d92b06cef13
Title: marie
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Marie(props) {
  const { nodes, materials } = useGLTF('/models/marie.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.37}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh geometry={nodes.Object_361.geometry} material={materials['24_base2_0.6_1_1']} skeleton={nodes.Object_361.skeleton} />
            <skinnedMesh geometry={nodes.Object_363.geometry} material={materials['24_eyes_2_1_1']} skeleton={nodes.Object_363.skeleton} />
            <skinnedMesh geometry={nodes.Object_365.geometry} material={materials['24_face_0.6_1_1']} skeleton={nodes.Object_365.skeleton} />
            <skinnedMesh geometry={nodes.Object_367.geometry} material={materials['24_skin_1_0_0']} skeleton={nodes.Object_367.skeleton} />
            <skinnedMesh geometry={nodes.Object_369.geometry} material={materials['25_alpha1_1_1_1']} skeleton={nodes.Object_369.skeleton} />
            <skinnedMesh geometry={nodes.Object_371.geometry} material={materials['25_alpha2_1_1_1']} skeleton={nodes.Object_371.skeleton} />
            <skinnedMesh geometry={nodes.Object_373.geometry} material={materials['25_alpha3_1_1_1']} skeleton={nodes.Object_373.skeleton} />
            <skinnedMesh geometry={nodes.Object_375.geometry} material={materials['25_alpha4_1_1_1']} skeleton={nodes.Object_375.skeleton} />
            <skinnedMesh geometry={nodes.Object_377.geometry} material={materials['25_hair4_0.6_1_1']} skeleton={nodes.Object_377.skeleton} />
            <skinnedMesh geometry={nodes.Object_378.geometry} material={materials['25_hair2_0.6_1_1']} skeleton={nodes.Object_378.skeleton} />
            <skinnedMesh geometry={nodes.Object_379.geometry} material={materials['25_hair6_0.6_1_1']} skeleton={nodes.Object_379.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/marie.glb')
