/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/offworld.glb 
Author: jameslucino117 (https://sketchfab.com/jameslucino117)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/creaturesoffworlddark-samusdark-samus-34-0fc1489275c445728ddeb62f7af68532
Title: Creatures>Offworld>Dark Samus>Dark Samus 3&4
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/offworld.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <group name="Aimingfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="CMDL_FAA12C05" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="CINF_4ABC8A50001" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_8" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.MAT_0_2} skeleton={nodes.Object_9.skeleton} />
                    {/* <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.MAT_0_3} skeleton={nodes.Object_10.skeleton} /> */}
                    <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.MAT_0_7} skeleton={nodes.Object_11.skeleton} />
                    <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.MAT_0_8} skeleton={nodes.Object_12.skeleton} />
                    <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.MAT_0_5} skeleton={nodes.Object_13.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/offworld.glb')
