/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/pool_mountains.glb 
Author: Vince_Crusty (https://sketchfab.com/vince.trust)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pool-in-the-mountains-baked-96537a370338456680c8327ec811733f
Title: Pool in the Mountains (Baked)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PoolMountains(props) {
  const { nodes, materials } = useGLTF("/models/pool_mountains.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.003"]}
        position={[3.335, -0.05, 1.565]}
        rotation={[-Math.PI, 0.786, -Math.PI]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials["Material.001"]}
        position={[3.335, -0.05, 1.565]}
        rotation={[-Math.PI, 0.786, -Math.PI]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.Skybox}
        position={[0.07, 1.327, 0.033]}
        rotation={[-Math.PI, -0.395, -Math.PI]}
        scale={0.021}
      />
    </group>
  );
}

useGLTF.preload("/models/pool_mountains.glb");
