/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/test-models/GrootModifiedCompressPlaceholder.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations, useTexture, Decal } from "@react-three/drei";
import { useControls } from "leva";

export function Groot2(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/test-models/GrootModifiedCompressPlaceholder.glb"
  );
  const { actions, mixer } = useAnimations(animations, group);
  const texture = useTexture("/images/dad.png");

  useEffect(() => {
    actions["mixamo.com"].play();
    mixer.timeScale = 1;
  }, [actions, mixer]);

  // useControls({
  //   angle: {
  //     min: 0,
  //     max: Math.PI * 2, // 360 degrees in radians
  //     value: 0,
  //     step: 0.01,
  //   },
  // });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.004}
        >
          <group name="Wave_Hip_Hop_Dancefbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="RetopoGroup1" />
                  <group name="Object_6">
                    <skinnedMesh
                      name="RetopoGroup1__0"
                      geometry={nodes.RetopoGroup1__0.geometry}
                      material={nodes.RetopoGroup1__0.material}
                      skeleton={nodes.RetopoGroup1__0.skeleton}
                    />
                    <skinnedMesh
                      name="RetopoGroup1__0_1"
                      geometry={nodes.RetopoGroup1__0_1.geometry}
                      skeleton={nodes.RetopoGroup1__0_1.skeleton}
                    >
                      <Decal
                        debug // Makes "bounding box" of the decal visible
                        position={[0, 650, 100]}
                        rotation={[0, 0.2, 0]} // (can be vector or degree in radians)
                        scale={[210, 210, 210]}
                      >
                        <meshBasicMaterial
                          map={texture}
                          polygonOffset
                          polygonOffsetFactor={-1} // The mesh should take precedence over the original
                        />
                      </Decal>
                    </skinnedMesh>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/test-models/GrootModifiedCompressPlaceholder.glb");
