/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/ayanami_4k.glb
Author: YU (https://sketchfab.com/pein)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ayanami-91cdc6379870408e8bfb2c2c22f586de
Title: Ayanami
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { DissolveMaterial } from "../dissolve/DissolveMaterial";

export function Ayanami4K(props) {
  const { nodes, materials } = useGLTF("/models/ayanami_4k.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[40.68, 1.31, -3.39]} rotation={[0.03, -0.22, 0.28]}>
        <mesh geometry={nodes["1_Material_#1_0"].geometry} scale={1.02}>
          <DissolveMaterial baseMaterial={materials.Material_1} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
        </mesh>
      </group>
      <mesh geometry={nodes["2_Material_#0_0"].geometry} scale={1.02}>
        <DissolveMaterial baseMaterial={materials.Material_0} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/ayanami_4k.glb");
