/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/coridor_interior_1k.glb
Author: Nikitos & 3130 (https://sketchfab.com/vrcityphoto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coridor-interior-189895b6289b4c839e90c7ad04a3bb25
Title: Coridor interior
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Coridor1K(props) {
  const { nodes, materials } = useGLTF("/models/coridor_interior_1k.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0.01, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials["Coridor.1001"]} />
        <mesh geometry={nodes.Object_3.geometry} material={materials["Coridor.1002"]} />
        <mesh geometry={nodes.Object_4.geometry} material={materials["Coridor.1003"]} />
        <mesh geometry={nodes.Object_5.geometry} material={materials["Coridor.1004"]} />
        <mesh geometry={nodes.Object_6.geometry} material={materials["Coridor.1005"]} />
      </group>
    </group>
  );
}

useGLTF.preload("/models/coridor_interior_1k.glb");
