/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/akira_motorcycle.glb
Author: Alikwill (https://sketchfab.com/Alikwill)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/akira-motorcycle-c2ea6a76f93d4158bdfb76dbb1613b5c
Title: Akira motorcycle
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function AkiraMotorcycle(props) {
  const { nodes, materials } = useGLTF('/models/akira_motorcycle.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={1}>
        <group position={[0, 0.06, 0.49]}>
          <mesh geometry={nodes.polySurface27_lambert2_0.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.polySurface28_phong2_0.geometry} material={materials.phong2} position={[0, -0.06, -0.16]} scale={[1.23, 1.07, 1.07]} />
        </group>
        <group position={[-0.15, 1.92, 0.82]} rotation={[0, 0.48, -0.13]} scale={0.25}>
          <mesh geometry={nodes.polySurface117_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.polySurface118_blinn2_0.geometry} material={materials.blinn2} />
          <mesh geometry={nodes.polySurface119_blinn1_0.geometry} material={materials.blinn1} />
          <mesh geometry={nodes.polySurface120_lambert2_0.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.polySurface121_lambert2_0.geometry} material={materials.lambert2} />
        </group>
        <group position={[0.02, 2.38, 0.86]} rotation={[0.23, -0.5, -2.81]} scale={0.25}>
          <mesh geometry={nodes.polySurface122_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.polySurface123_blinn2_0.geometry} material={materials.blinn2} />
          <mesh geometry={nodes.polySurface124_blinn1_0.geometry} material={materials.blinn1} />
          <mesh geometry={nodes.polySurface125_lambert2_0.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.polySurface126_lambert2_0.geometry} material={materials.lambert2} />
        </group>
        <group position={[0, 1.17, 0.59]} scale={[0.6, 0.55, 1.78]}>
          <mesh geometry={nodes.polySurface29_blinn1_0.geometry} material={materials.blinn1} />
          <mesh geometry={nodes.polySurface30_blinn2_0.geometry} material={materials.blinn2} scale={[0.93, 1, 1]} />
        </group>
        <group position={[0.21, 0, 0]}>
          <mesh geometry={nodes.polySurface129_blinn1_0.geometry} material={materials.blinn1} />
          <mesh geometry={nodes.polySurface130_blinn1_0.geometry} material={materials.blinn1} />
        </group>
        <mesh geometry={nodes.pCylinder32_phong5_0.geometry} material={materials.phong5} position={[0, 1.83, 1.55]} rotation={[1.83, 0, 0]} scale={[1.06, 0.98, 1.45]} />
        <mesh geometry={nodes.pCube37_blinn2_0.geometry} material={materials.blinn2} position={[-0.01, 0.94, 0.14]} scale={[1.34, 0.5, 3.05]} />
        <mesh geometry={nodes.pCube38_lambert2_0.geometry} material={materials.lambert2} position={[0, 2.42, -1.6]} rotation={[-0.18, 0, 0]} scale={[0.68, 0.44, 0.15]} />
        <mesh geometry={nodes.pCube39_lambert2_0.geometry} material={materials.lambert2} position={[0, 1.8, -1.47]} rotation={[-0.2, 0, 0]} scale={[0.76, 0.87, 0.15]} />
        <mesh geometry={nodes.pCube41_blinn2_0.geometry} material={materials.blinn2} position={[0, 1.99, 0.64]} rotation={[0.13, 0, 0]} scale={[0.93, 0.39, 0.35]} />
        <mesh geometry={nodes.pCylinder33_blinn1_0.geometry} material={materials.blinn1} position={[0, 1.8, 1.49]} rotation={[1.83, 0, 0]} scale={[1.08, 1, 1.48]} />
        <mesh geometry={nodes.pCube45_blinn1_0.geometry} material={materials.blinn1} position={[0.12, 0.91, -0.01]} scale={[1.34, 0.5, 3.05]} />
        <mesh geometry={nodes.pCube47_blinn2_0.geometry} material={materials.blinn2} position={[0, 0.47, -0.63]} rotation={[-0.05, 0, 0]} scale={[0.94, 0.16, 1.05]} />
        <mesh geometry={nodes.pCube49_lambert2_0.geometry} material={materials.lambert2} position={[0.65, 1.88, -1.34]} rotation={[-0.2, -0.35, 0.03]} scale={[1.17, 0.74, 0.16]} />
        <mesh geometry={nodes.pCube51_blinn2_0.geometry} material={materials.blinn2} position={[0, 1.96, 1.54]} rotation={[0.07, 0, 0]} scale={[0.8, 0.47, 1]} />
        <mesh geometry={nodes.pCube52_blinn2_0.geometry} material={materials.blinn2} position={[0, 2.1, 1.97]} rotation={[0.06, 0, 0]} scale={[0.7, 0.22, 0.51]} />
        <mesh geometry={nodes.pCube64_lambert1_0.geometry} material={materials.lambert1} position={[-0.11, 1.58, 0.48]} rotation={[-0.48, 0, 0]} scale={[0.14, 0.07, 0.14]} />
        <mesh geometry={nodes.pCube65_lambert1_0.geometry} material={materials.lambert1} position={[0.02, 0.06, -0.03]} />
        <mesh geometry={nodes.pCylinder47_lambert1_0.geometry} material={materials.lambert1} position={[0.13, 1.53, 0.5]} rotation={[-0.46, 0, 0]} scale={[0.04, 0.01, 0.04]} />
        <mesh geometry={nodes.pCube66_lambert2_0.geometry} material={materials.lambert2} position={[-0.45, 0.65, 1.11]} rotation={[-0.75, 0, 0]} scale={[0.21, 0.01, 0.54]} />
        <mesh geometry={nodes.pCube67_lambert2_0.geometry} material={materials.lambert2} position={[0.45, 0.65, 1.11]} rotation={[-0.75, 0, 0]} scale={[0.21, 0.01, 0.54]} />
        <mesh geometry={nodes.pCylinder48_blinn1_0.geometry} material={materials.blinn1} position={[0, 0.95, 0.21]} rotation={[0, 0, -Math.PI / 2]} scale={[0.1, 0.24, 0.1]} />
        <mesh geometry={nodes.pCube79_lambert2_0.geometry} material={materials.lambert2} position={[0.01, -3.23, 1.21]} rotation={[-0.24, 0, 0]} />
        <mesh geometry={nodes.pCube80_lambert2_0.geometry} material={materials.lambert2} position={[0.35, 0.9, -1.2]} rotation={[-0.3, -0.94, -0.05]} scale={[0.41, 1.4, 0.2]} />
        <mesh geometry={nodes.pCube81_lambert2_0.geometry} material={materials.lambert2} />
        <mesh geometry={nodes.pCube82_lambert2_0.geometry} material={materials.lambert2} position={[-0.09, 0, 0]} />
        <mesh geometry={nodes.polySurface112_lambert2_0.geometry} material={materials.lambert2} position={[-0.03, -3.14, -5.01]} scale={[1.1, 1.72, 1.72]} />
        <mesh geometry={nodes.polySurface113_lambert2_0.geometry} material={materials.lambert2} />
        <mesh geometry={nodes.polySurface114_phong2_0.geometry} material={materials.phong2} position={[0, -0.06, 0.18]} scale={[1.05, 1.06, 1.06]} />
        <mesh geometry={nodes.pCylinder58_blinn1_0.geometry} material={materials.blinn1} />
        <mesh geometry={nodes.pCylinder59_blinn1_0.geometry} material={materials.blinn1} />
        <mesh geometry={nodes.pCube84_blinn1_0.geometry} material={materials.blinn1} position={[0.62, 0, 0]} />
        <mesh geometry={nodes.pCube85_blinn2_0.geometry} material={materials.blinn2} position={[0, 1.29, -1.62]} rotation={[-0.14, 0, 0]} scale={[1, 1.35, 0.11]} />
        <mesh geometry={nodes.pCylinder62_blinn1_0.geometry} material={materials.blinn1} />
        <mesh geometry={nodes.pCylinder63_blinn1_0.geometry} material={materials.blinn1} />
        <mesh geometry={nodes.polySurface127_blinn1_0.geometry} material={materials.blinn1} />
        <mesh geometry={nodes.polySurface128_blinn1_0.geometry} material={materials.blinn1} />
        <mesh geometry={nodes.polySurface116_blinn1_0.geometry} material={materials.blinn1} />
        <mesh geometry={nodes.pCube88_phong3_0.geometry} material={materials.phong3} position={[0.17, 2.62, -1.93]} rotation={[0, 0, -0.71]} scale={[0.2, 0.15, 0.1]} />
        <mesh geometry={nodes.pCube89_phong3_0.geometry} material={materials.phong3} position={[-0.16, 2.62, -1.93]} rotation={[0, 0, Math.PI / 4]} scale={[0.2, 0.15, 0.1]} />
        <mesh geometry={nodes.pCube90_phong4_0.geometry} material={materials.phong4} position={[0, 2.12, 2.22]} rotation={[0.06, 0, 0]} scale={[0.27, 0.13, 0.09]} />
        <mesh geometry={nodes.polySurface131_lambert2_0.geometry} material={materials.lambert2} position={[-0.04, -3.67, -11.98]} scale={[2, 1.97, 1.97]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/akira_motorcycle.glb')
