/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/low_poly_race_track.glb
Author: Quarks Studios (https://sketchfab.com/QuarksStudios)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-race-track-b40628339fde4b2fbe41711edc7c7a93
Title: Low poly race track
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RaceTrack(props) {
  const { nodes, materials } = useGLTF('/models/low_poly_race_track.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[1566.06, 196.45, -3529.2]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-13817.65, 196.45, 7453.29]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube001_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube001_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cube001_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[17227.74, 196.45, 32542.19]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
            <mesh geometry={nodes.Cube002_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube002_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[15013.7, 196.45, 14883.67]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
            <mesh geometry={nodes.Cube003_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube003_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[6962.13, 196.45, 1568.77]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cube011_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube011_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cube011_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-2733.94, 196.45, -3529.2]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube012_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube012_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-3626.91, 196.45, -3330.4]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
            <mesh geometry={nodes.Cube013_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube013_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cube013_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-8722.9, 196.45, 2065.28]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cube004_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube004_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-14703.88, 196.45, 7651.56]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
            <mesh geometry={nodes.Cube005_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube005_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-15595.63, 196.45, 7849.48]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
            <mesh geometry={nodes.Cube006_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube006_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cube006_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-20492.14, 196.45, 9786.93]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cube007_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube007_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cube007_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-15103.88, 196.45, 14884.29]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
            <mesh geometry={nodes.Cube008_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube008_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[23671.54, 196.45, 14884.29]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
            <mesh geometry={nodes.Cube009_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube009_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[29048.49, 196.45, 19979]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cube010_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube010_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cube010_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[29248.16, 196.45, 20862.81]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cube014_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube014_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[24152.19, 196.45, 32343.12]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube015_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube015_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cube015_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[21547.49, 196.45, 32541.87]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
            <mesh geometry={nodes.Cube016_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube016_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[5500.9, 196.45, 32584.36]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube017_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube017_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[7162.54, 196.45, 2458.46]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cube018_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube018_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[7162.54, 196.45, 6785.28]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cube019_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube019_Material_0.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube019_Material005_0.geometry} material={materials['Material.005']} />
          </group>
          <group position={[7162.54, 196.45, 11109.57]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cube020_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube020_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[2066.72, 196.45, 20802.39]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube021_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube021_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cube021_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[1566.06, 196.45, 21003.53]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube022_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube022_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[675.86, 196.45, 21203.78]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
            <mesh geometry={nodes.Cube023_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube023_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cube023_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-4420.16, 196.45, 26595.67]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cube024_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube024_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-4220.75, 196.45, 27486.93]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cube025_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube025_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cube025_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[1173.29, 196.45, 32584.77]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube026_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube026_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[29248.16, 196.45, 23930]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cube027_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube027_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[24568.31, 196.45, 32541.87]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
            <mesh geometry={nodes.Cube028_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube028_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[29248.16, 196.45, 26962.81]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cube029_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube029_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[7162.54, 196.45, 15404.27]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cube030_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube030_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-10761.16, 196.45, 14884.29]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
            <mesh geometry={nodes.Cube031_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube031_Material_0.geometry} material={materials.Material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/low_poly_race_track.glb')
