/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/modern_city_block.glb
Author: akselmot (https://sketchfab.com/akselmot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-city-block-c80dba249d9547cbb48d00828d23cfa7
Title: Modern City Block
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CityBlock(props) {
  const { nodes, materials } = useGLTF('/models/modern_city_block.glb')
  return (
    <group {...props} dispose={null} scale={0.01}>
      <group position={[-9364.87, 4071.9, 32018.56]} rotation={[-Math.PI / 2, 0, -2.43]} scale={100}>
        <mesh geometry={nodes.Plane057_4_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Plane057_3_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Plane057_2_0.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Plane057_1_0.geometry} material={materials.material_3} />
      </group>
      <group position={[2340.77, 3607.79, 22216.29]} rotation={[-Math.PI / 2, 0, 0.74]} scale={100}>
        <mesh geometry={nodes.Plane056_4_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Plane056_2_0.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Plane056_3_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Plane056_1_0.geometry} material={materials.material_3} />
      </group>
      <group position={[-20992.2, 4048.2, 24447.97]} rotation={[-Math.PI / 2, 0, 0.74]} scale={100}>
        <mesh geometry={nodes.Cube009_4_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Cube009_2_0.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Cube009_3_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Cube009_1_0.geometry} material={materials.material_3} />
      </group>
      <group position={[8233.97, 4622.25, 10918.82]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Cube_4_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Cube_2_0.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Cube_3_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Cube_1_0.geometry} material={materials.material_3} />
      </group>
      <group position={[-13726.88, 3467.31, 18715.27]} rotation={[-Math.PI / 2, 0, 0.75]} scale={100}>
        <mesh geometry={nodes.Plane001_2_0.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Plane001_3_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Plane001_1_0.geometry} material={materials.material_3} />
      </group>
      <group position={[-3460.28, 3468.02, 11181.68]} rotation={[-Math.PI / 2, 0, 0.71]} scale={100}>
        <mesh geometry={nodes.Plane036_3_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Plane036_2_0.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Plane036_1_0.geometry} material={materials.material_3} />
      </group>
      <group position={[4283.74, 5551.26, 2292.18]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Cube192_3_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Cube192_7_0.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Cube192_2_0.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Cube192_1_0.geometry} material={materials.material_3} />
      </group>
      <group position={[-8124.78, 3650.49, 2779.92]} rotation={[-Math.PI / 2, 0, 0.74]} scale={100}>
        <mesh geometry={nodes.Plane048_3_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Plane048_2_0.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Plane048_1_0.geometry} material={materials.material_3} />
      </group>
      <group position={[-21598.1, 4956.98, 12792.47]} rotation={[-Math.PI / 2, 0, 0.75]} scale={100}>
        <mesh geometry={nodes.Cube002_7_0.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Cube002_2_0.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Cube002_3_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Cube002_1_0.geometry} material={materials.material_3} />
      </group>
      <group position={[-8452.37, -18.81, 12080.66]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.fences_3_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.fences_6_0.geometry} material={materials.material_5} />
      </group>
      <group position={[-12130.83, -59.31, 9716.06]} rotation={[-Math.PI / 2, 0, 0.37]} scale={100}>
        <mesh geometry={nodes.bridge_5_0.geometry} material={materials.material_6} />
        <mesh geometry={nodes.bridge_6_0.geometry} material={materials.material_5} />
      </group>
      <group position={[-9983.08, -230.72, 15842.27]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.terrain_5_0.geometry} material={materials.material_6} />
        <mesh geometry={nodes.terrain_6_0.geometry} material={materials.material_5} />
        <mesh geometry={nodes.terrain_4_0.geometry} material={materials.material} />
      </group>
      <group position={[12814.62, -68.96, 1192.42]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Plane061_7_0.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Plane061_4_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Plane061_5_0.geometry} material={materials.material_6} />
        <mesh geometry={nodes.Plane061_6_0.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Plane061_1_0.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Plane061_2_0.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Plane061_3_0.geometry} material={materials.material_1} />
      </group>
      <mesh geometry={nodes.dec001_6_0.geometry} material={materials.material_5} position={[-6030.89, -60.76, 15546.99]} rotation={[-Math.PI / 2, 0, 0.76]} scale={635.86} />
      <mesh geometry={nodes.markup_6_0.geometry} material={materials.material_5} position={[-4560.74, -78.14, 13815.17]} rotation={[-Math.PI / 2, 0, 0.75]} scale={424.45} />
      <mesh geometry={nodes.borders_6_0.geometry} material={materials.material_5} position={[-4601.38, -62.44, 13783.84]} rotation={[-Math.PI / 2, 0, -0.81]} scale={100} />
      <mesh geometry={nodes.pillars_6_0.geometry} material={materials.material_5} position={[-12534.58, -343.84, 9555.83]} rotation={[-Math.PI / 2, 0, 0.37]} scale={100} />
      <mesh geometry={nodes.roads_5_0.geometry} material={materials.material_6} position={[-4560.93, -78.56, 13815.26]} rotation={[-Math.PI / 2, 0, 0.75]} scale={424.45} />
    </group>
  )
}

useGLTF.preload('/models/modern_city_block.glb')
