/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/idahome/beachball.glb 
Author: wildheart107 (https://sketchfab.com/wildheart107)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/beachball-ee18423fb5a54fa6bfb07094848feb70
Title: Beachball
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Beachball(props) {
  const { nodes, materials } = useGLTF("/idahome/models/beachball.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials["Material.001"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/idahome/models/beachball.glb");
