/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/pool_mountains.glb 
Author: Vince_Crusty (https://sketchfab.com/vince.trust)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pool-in-the-mountains-baked-96537a370338456680c8327ec811733f
Title: Pool in the Mountains (Baked)
*/

import React from "react";
import * as THREE from "three";
import { useGLTF, useTexture } from "@react-three/drei";

export function PoolMountains({ position, rotY, bgRes }) {
  const { nodes, materials } = useGLTF("/models/idahome/pool_mountains_4k.glb");

  const texture = useTexture(
    bgRes === "high"
      ? "./images/idahome/boise-5k.jpg"
      : bgRes === "mid"
      ? "./images/idahome/boise-4k.jpg"
      : bgRes === "low"
      ? "./images/idahome/boise-3k.jpg"
      : "./images/idahome/boise-3k.jpg"
  );
  texture.repeat.set(1, 1);
  texture.wrapS = texture.wrapT = THREE.RepeatWrapping;

  return (
    <group position={position} rotation-y={rotY} dispose={null}>
      {/* <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.003"]}
        position={[3.335, -0.05, 1.565]}
        rotation={[-Math.PI, 0.786, -Math.PI]}
      /> */}
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials["Material.001"]}
        position={[3.335, -0.05, 1.565]}
        rotation={[-Math.PI, 0.786, -Math.PI]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        // material={materials.Skybox}
        position={[0.07, 1.327, 0.033]}
        rotation={[-Math.PI, -0.395, -Math.PI]}
        scale={0.021}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/idahome/pool_mountains_4k.glb");
