/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/ayanami_rei.glb
Author: CheRa (https://sketchfab.com/chera3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ayanami-rei-c91af77c611e4928a275ac26f90fc6ac
Title: Ayanami Rei
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/ayanami_rei.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        {/* <mesh geometry={nodes.Object_2.geometry} material={materials.Bandage} /> */}
        <mesh geometry={nodes.Object_3.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Face} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Hair} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/ayanami_rei.glb')
