/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/high/clockdoor.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Clockdoor(props) {
  const { nodes, materials } = useGLTF('/models/high/clockdoor.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.big_closet_clock_1.geometry} material={materials.plastic_mat} />
        <mesh geometry={nodes.big_closet_clock_2.geometry} material={materials.handles_metal_mat} />
        <mesh geometry={nodes.big_closet_clock_3.geometry} material={materials.clock_metal_mat} />
        <mesh geometry={nodes.big_closet_clock_4.geometry} material={materials.hinges_metal_mat} />
        <mesh geometry={nodes.big_closet_clock_5.geometry} material={materials.base_wooden_mat} />
        <mesh geometry={nodes.big_closet_clock_6.geometry} material={materials.top_wooden_mat} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/high/clockdoor.glb')
