/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/abbey-door.glb 
Author: noxfcna (https://sketchfab.com/noxfcna)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/secondary-door-westminster-abbey-af70ab0d5ce140dc88dcce77f7813c17
Title: Secondary door -  Westminster Abbey
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Door(props) {
  const { nodes, materials } = useGLTF('/models/abbey-door.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.114, 0.087, -7.417]} rotation={[-1.547, -0.005, -3.129]}>
        <group position={[-3.59, 2.683, -2.371]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.material_1} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.material_2} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.material_3} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/abbey-door.glb')
