/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/dragon_animation_flying.glb
Author: Al-Deezel (https://sketchfab.com/Al-dezel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dragon-animation-flying-2fdae78e272c4994bb67336a289f11ef
Title: Dragon Animation Flying
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function DragonFlying({ props, dragonRef, position }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/dragon_flying.glb");
  const { actions, mixer } = useAnimations(animations, group);

  useEffect(() => {
    actions["flying"].play();
    mixer.timeScale = 1;
  }, [actions, mixer]);

  return (
    <group ref={dragonRef} position={position}>
      <group
        ref={group}
        {...props}
        dispose={null}
        rotation={[0, Math.PI, 0]}
        position-y={-0.7}
      >
        <group name="Sketchfab_Scene">
          <group
            name="Sketchfab_model"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.32}
          >
            <group name="root">
              <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                <group name="RootNode0_0" scale={0.01}>
                  <group name="skeletal3_3">
                    <group name="GLTF_created_0">
                      <primitive object={nodes.GLTF_created_0_rootJoint} />
                      <group name="dragon_wings22_2_correction">
                        <group name="dragon_wings22_2" />
                      </group>
                      <skinnedMesh
                        name="Object_228"
                        geometry={nodes.Object_228.geometry}
                        skeleton={nodes.Object_228.skeleton}
                      >
                        <meshPhongMaterial color={"cyan"} />
                      </skinnedMesh>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/dragon_flying.glb");
