/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/dragon_fantasy.glb 
Author: Prof.v7x (https://sketchfab.com/profesor_v7x)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dragon-fantasy-ffe005ed8976412cb81c19d9395c00ae
Title: Dragon Fantasy
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function DragonFantasy(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/dragon_fantasy.glb"
  );
  const { actions,mixer } = useAnimations(animations, group);
  // action= JiNengGongJi1,JiNengGongJi2,PuTongGongJi,SiWang,XingZou,ZhanLi
  useEffect(() => {
    actions["JiNengGongJi2"].play();
    mixer.timeScale = 0.5;
  }, [actions, mixer]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          scale={20.91}
        >
          <group name="drgonfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.BossLeiLong}
                    skeleton={nodes.Object_7.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/dragon_fantasy.glb");
