/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/earth_tank_2k.glb 
Author: TankBasedConvexSF (https://sketchfab.com/Sany4)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/earth-e226c8d612424c9fb80b760905e3a6f2
Title: Earth
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function EarthTank2k(props) {
  const { nodes, materials } = useGLTF("/models/earth_tank_2k.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Earth_0.geometry} material={materials.Physical} />
        <mesh
          geometry={nodes.Clouds_0.geometry}
          material={materials.Physical3}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/earth_tank_2k.glb");
