/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/extrasoundpro.glb 
Author: Nikitos & 3130 (https://sketchfab.com/vrcityphoto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/extrasoundpro-e32364a157ac40a8a7ca6c4d1a95ef58
Title: EXTRASOUNDPRO
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ExtraSoundPro(props) {
  const { nodes, materials } = useGLTF("/models/extrasoundpro.glb");
  return (
    <group>
      <group
        {...props}
        dispose={null}
        position={[-36, -4.05, -100]}
        scale={0.01}
      >
        <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
          <group position={[0, 0, 0]}>
            <mesh
              geometry={nodes.Object_3.geometry}
              material={materials.baked_Global2}
            />
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials.baked_Global2}
            />
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials.baked_Global2}
            />
            <mesh
              geometry={nodes.Object_6.geometry}
              material={materials.baked_Global2}
            />
            <mesh
              geometry={nodes.Object_7.geometry}
              material={materials.baked_Global2}
            />
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials.baked_Global2}
            />
            <mesh
              geometry={nodes.Object_9.geometry}
              material={materials.baked_Global2}
            />
            <mesh
              geometry={nodes.Object_10.geometry}
              material={materials.baked_HROM}
            />
            <mesh
              geometry={nodes.Object_11.geometry}
              material={materials.baked_HROM}
            />
            <mesh
              geometry={nodes.Object_12.geometry}
              material={materials.baked_HROM}
            />
            <mesh
              geometry={nodes.Object_13.geometry}
              material={materials.baked_HROM}
            />
            <mesh
              geometry={nodes.Object_14.geometry}
              material={materials.baked_HROM}
            />
            <mesh
              geometry={nodes.Object_15.geometry}
              material={materials.baked_LEPNINA_biegeW}
            />
            <mesh
              geometry={nodes.Object_16.geometry}
              material={materials.baked_Material__311}
            />
            <mesh
              geometry={nodes.Object_17.geometry}
              material={materials.baked_stols}
            />
            <mesh
              geometry={nodes.Object_18.geometry}
              material={materials.wire_057008136}
            />
            <mesh
              geometry={nodes.Object_19.geometry}
              material={materials.wire_057008136}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/extrasoundpro.glb");
