/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/fear_crawl.glb 
Author: alex.andain.777 (https://sketchfab.com/alex.andain.777)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fear-crawler-all-animation-it-takes-to-9f5dc82f62f148f7a53504f50c439eab
Title: Fear Crawler All animation It Takes to
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function FearCrawl(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/fear_crawl.glb')
  const { actions, mixer } = useAnimations(animations, group)
  useEffect(() => {
    actions["FearCrawler.ao|Enemies_Basement_FearCrawler_Crawl_Fwd"].play();
    mixer.timeScale = 0.4;
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="b6fdf511ec77460ab190ad6b1f95c6a9fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="FearCrawlerao" rotation={[-Math.PI / 2, 0, 0]} scale={10}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_290" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_291" geometry={nodes.Object_291.geometry} material={materials.FearCrawler} skeleton={nodes.Object_291.skeleton} />
                    <skinnedMesh name="Object_292" geometry={nodes.Object_292.geometry} material={materials.FearCrawler} skeleton={nodes.Object_292.skeleton} />
                    <skinnedMesh name="Object_293" geometry={nodes.Object_293.geometry} material={materials.FearCrawler} skeleton={nodes.Object_293.skeleton} />
                    <skinnedMesh name="Object_294" geometry={nodes.Object_294.geometry} material={materials.FearCrawler} skeleton={nodes.Object_294.skeleton} />
                    <skinnedMesh name="Object_295" geometry={nodes.Object_295.geometry} material={materials.FearCrawler} skeleton={nodes.Object_295.skeleton} />
                  </group>
                </group>
                <group name="FearCrawlermo" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/fear_crawl.glb')
