/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/floating_portal_island.glb 
Author: Myjato (https://sketchfab.com/Myjato)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/floating-portal-island-diorama-62cade7753204cfc9589fa12a6b8b7df
Title: Floating Portal Island | diorama
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function FloatingIslandPortal(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/floating_portal_island.glb"
  );
  const { actions, mixer } = useAnimations(animations, group);

  useEffect(() => {
    actions["Take 001"].play();
    mixer.timeScale = 0.4;
  });

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position-y={-1.6}
      rotation-y={-0.7}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="3beb0b94f77a4fafa185b3857fb737e2fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="group1">
                  <group name="FlyingPiece" position={[2.016, 9.59, -0.893]}>
                    <mesh
                      name="FlyingPiece_portal_0"
                      geometry={nodes.FlyingPiece_portal_0.geometry}
                      material={materials.portal}
                    />
                  </group>
                  <group name="Rock2" position={[-6.142, 9.164, -1.58]}>
                    <mesh
                      name="Rock2_lambert1_0"
                      geometry={nodes.Rock2_lambert1_0.geometry}
                      material={materials.lambert1}
                    />
                  </group>
                  <group name="Rock1" position={[-3.441, 4.417, 5.67]}>
                    <mesh
                      name="Rock1_lambert1_0"
                      geometry={nodes.Rock1_lambert1_0.geometry}
                      material={materials.lambert1}
                    />
                  </group>
                  <group name="Rock3" position={[1.109, 6.567, -6.575]}>
                    <mesh
                      name="Rock3_lambert1_0"
                      geometry={nodes.Rock3_lambert1_0.geometry}
                      material={materials.lambert1}
                    />
                  </group>
                  <group name="Rock4" position={[6.725, 6.339, -2.723]}>
                    <mesh
                      name="Rock4_lambert1_0"
                      geometry={nodes.Rock4_lambert1_0.geometry}
                      material={materials.lambert1}
                    />
                  </group>
                  <group name="Base">
                    <mesh
                      name="Base_portal_0"
                      geometry={nodes.Base_portal_0.geometry}
                      material={materials.portal}
                    />
                  </group>
                  <group name="Base1">
                    <mesh
                      name="Base1_lambert1_0"
                      geometry={nodes.Base1_lambert1_0.geometry}
                      material={materials.lambert1}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/floating_portal_island.glb");
