/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/ftmLow.glb -r public
Author: luyssport (https://sketchfab.com/luyssport)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/ftm-0970f30574d047b1976ba0aa6f2ef855
Title: Ftm
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function FtmLow(props) {
  const { nodes, materials } = useGLTF("/models/ftmLow.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.25}>
        <mesh geometry={nodes.character_0.geometry} material={materials.roof} position={[2.11, 4.37, -1.14]} />
        <mesh geometry={nodes.sky_0.geometry} material={materials.material_10} rotation={[0, 0, -0.1]} scale={0.55} />
        <mesh geometry={nodes.ground_0.geometry} material={materials.ground} position={[1.98, -3.33, 0]} />
        <mesh geometry={nodes.tree_leaves_0.geometry} material={materials.tree_leaves} position={[1.98, -3.33, 0]} />
        <mesh geometry={nodes.tree_leaves_inv_0.geometry} material={materials.tree_leaves} position={[1.98, -3.33, 0]} />
        <mesh geometry={nodes.roof_0.geometry} material={materials.roof} position={[1.98, -3.33, 0]} />
        <mesh geometry={nodes.madera_0.geometry} material={materials.madera} position={[1.98, -3.33, 0]} />
        <mesh geometry={nodes.piedras_0.geometry} material={materials.piedras} position={[1.98, -3.33, 0]} />
        <mesh geometry={nodes.dec_0.geometry} material={materials.material} position={[1.98, -3.33, 0]} />
        <mesh geometry={nodes.outline_0.geometry} material={materials.outline} position={[1.98, -3.33, 0]} />
        <mesh geometry={nodes.monster_001_0.geometry} material={materials.monster_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.monster_0.geometry} material={materials.monster} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.eyes002_0.geometry} material={materials.eyes002} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  );
}

useGLTF.preload("/models/ftmLow.glb");
