/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/grid_city.glb 
Author: Miguelangelo Rosario (https://sketchfab.com/miguelangelo2k)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grid-city-7875ebc750ca4ab2971c2e0d38b80223
Title: Grid City
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function GridCity(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/grid_city.glb");
  const { actions, mixer } = useAnimations(animations, group);

  useEffect(() => {
    actions["Take 001"].play();
    mixer.timeScale = 0.1;
  }, [actions, mixer]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, Math.PI, 0]}
          scale={0.167}
        >
          <group
            name="2a4e65486c974c60925f49ce91f5445bfbx"
            rotation={[-Math.PI, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Tube001">
                  <group name="Object_5" rotation={[0, Math.PI / 2, 0]}>
                    <mesh
                      name="Tube001_01_-_Default_0"
                      geometry={nodes["Tube001_01_-_Default_0"].geometry}
                      material={materials["01_-_Default"]}
                    />
                    <mesh
                      name="Tube001_01_-_Default_0_1"
                      geometry={nodes["Tube001_01_-_Default_0_1"].geometry}
                      material={materials["01_-_Default"]}
                    />
                    <mesh
                      name="Tube001_01_-_Default_0_2"
                      geometry={nodes["Tube001_01_-_Default_0_2"].geometry}
                      material={materials["01_-_Default"]}
                    />
                    <mesh
                      name="Tube001_01_-_Default_0_3"
                      geometry={nodes["Tube001_01_-_Default_0_3"].geometry}
                      material={materials["01_-_Default"]}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/grid_city.glb");
