/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/mma_kick.glb 
Author: glooriashanda (https://sketchfab.com/glooriashanda)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mma-kick-e8373afef8464ee49ea8ace7b14a4260
Title: MMA KICK
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Kick(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/mma_kick.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_91">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="EyeLeft_82" />
                  <group name="EyeRight_83" />
                  <group name="Wolf3D_Body_84" />
                  <group name="Wolf3D_Hair_85" />
                  <group name="Wolf3D_Head_86" />
                  <group name="Wolf3D_Outfit_Bottom_87" />
                  <group name="Wolf3D_Outfit_Footwear_88" />
                  <group name="Wolf3D_Outfit_Top_89" />
                  <group name="Wolf3D_Teeth_90" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Object_11.skeleton} />
                  <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Object_13.skeleton} />
                  <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Object_15.skeleton} />
                  <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Object_17.skeleton} />
                  <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Object_19.skeleton} />
                  <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Object_21.skeleton} />
                  <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Object_23.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/mma_kick.glb')
