/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/lava_planet.glb -r public
Author: jcises (https://sketchfab.com/jcises)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/lava-planet-f266cfb9baab4f7390c08724aea78b5b
Title: lava planet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LavaPlanet(props) {
  const { nodes, materials } = useGLTF('/models/lava_planet.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/lava_planet.glb')
