/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/medieval_sci-fi_pillar.glb 
Author: Nick.Amalin (https://sketchfab.com/Nick.Amalin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-sci-fi-pillar-60c1b1f74df24898a54968ec3008fc63
Title: Medieval Sci-fi Pillar
*/

import { useRef } from "react";
import * as THREE from "three";
import { useGLTF, useHelper } from "@react-three/drei";

export function MedievalSciFiPillar(props) {
  const { nodes, materials } = useGLTF("/models/medieval_sci-fi_pillar.glb");

  const pointLight = useRef();
  // useHelper(pointLight, THREE.PointLightHelper, 1, "red");

  return (
    <group {...props} dispose={null}>
      <pointLight ref={pointLight} position={[0, 4, 0]} intensity={2} />
      <mesh
        geometry={nodes.pCylinder4_Blue_neon_0.geometry}
        material={materials.Blue_neon}
      />
      <mesh
        geometry={nodes.pCylinder4_Metaltexture01_0.geometry}
        material={materials.Metaltexture01}
      />
    </group>
  );
}

useGLTF.preload("/models/medieval_sci-fi_pillar.glb");
