/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/mega_wyvern.glb 
Author: ArachnoBoy (https://sketchfab.com/vang807)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/mega-wyvern-f8caf90ad5da4017b0dddfe880cf37cc
Title: Mega Wyvern
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function MegaWyvern(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/mega_wyvern.glb");
  const { actions, mixer } = useAnimations(animations, group);

  // Actions
  // Appearance,Beam|Roar,Combo Hit,Death,Fire Balls,Flame Blast,Idle,Roar,Strike Swoop,Talon Smash,Wind Blast|Wing Slap,
  useEffect(() => {
    actions["Idle"].play();
    mixer.timeScale = 1;
  }, [actions, mixer]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.997}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Sketchfab_model_0"
                rotation={[-Math.PI / 2, 0, 0]}
                scale={46.949}
              >
                <group
                  name="Dragon_Boss_05fbx_1"
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                >
                  <group name="Object_2_2">
                    <group name="RootNode_3">
                      <group name="Dragon_Boss_05_4">
                        <group name="Object_5_5">
                          <group name="GLTF_created_0">
                            <primitive
                              object={nodes.GLTF_created_0_rootJoint}
                            />
                            <group name="Object_8_8_correction">
                              <group name="Object_8_8" />
                            </group>
                            <skinnedMesh
                              name="Object_82"
                              geometry={nodes.Object_82.geometry}
                              material={materials.Dragon_Boss_05}
                              skeleton={nodes.Object_82.skeleton}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/mega_wyvern.glb");
