/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/model.glb 
Author: huseyn33 (https://sketchfab.com/huseyn33)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/c-model-husein33--es4-46233c75bdc54699a18aa4df4d8be78f
Title: c_model husein33 _es4
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/model.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.268, 0, 0.049]} rotation={[Math.PI / 2, 0, 0]} scale={0.972}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['0-_0-_28']} />
            <mesh geometry={nodes.Object_5.geometry} material={materials['5-_9-_UniqueID_7']} />
            <mesh geometry={nodes.Object_6.geometry} material={materials['4-_8-_UniqueID_7']} />
            <mesh geometry={nodes.Object_7.geometry} material={materials['3-_5-_UniqueID_7']} />
            <mesh geometry={nodes.Object_8.geometry} material={materials['2-_4-_UniqueID_7']} />
            <mesh geometry={nodes.Object_9.geometry} material={materials['1-_1-_UniqueID_7']} />
          </group>
          <group position={[-0.229, 1.39, 0.114]} rotation={[1.872, -0.238, -0.161]} scale={1.067}>
            <mesh geometry={nodes.Object_11.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.material_0} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/model.glb')
