/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/pulse.glb 
Author: tamminen (https://sketchfab.com/tamminen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pulse-ea875d1cbe4b4528803ab414fccccfb9
Title: Pulse
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Pulse(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/pulse.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Plane_0" position={[1, 0, 0]}>
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane001_2" position={[-1, 0, 0]}>
                <mesh
                  name="Object_6"
                  geometry={nodes.Object_6.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane002_4" position={[0, 0, -1]}>
                <mesh
                  name="Object_8"
                  geometry={nodes.Object_8.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane003_6" position={[0, 0, 1]}>
                <mesh
                  name="Object_10"
                  geometry={nodes.Object_10.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane004_8" position={[0.707, 0, -0.707]}>
                <mesh
                  name="Object_12"
                  geometry={nodes.Object_12.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane005_10" position={[-0.707, 0, 0.707]}>
                <mesh
                  name="Object_14"
                  geometry={nodes.Object_14.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane006_12" position={[-0.707, 0, -0.707]}>
                <mesh
                  name="Object_16"
                  geometry={nodes.Object_16.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane007_14" position={[0.707, 0, 0.707]}>
                <mesh
                  name="Object_18"
                  geometry={nodes.Object_18.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane008_16" position={[0.924, 0, -0.383]}>
                <mesh
                  name="Object_20"
                  geometry={nodes.Object_20.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane009_18" position={[-0.924, 0, 0.383]}>
                <mesh
                  name="Object_22"
                  geometry={nodes.Object_22.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane010_20" position={[-0.383, 0, -0.924]}>
                <mesh
                  name="Object_24"
                  geometry={nodes.Object_24.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane011_22" position={[0.383, 0, 0.924]}>
                <mesh
                  name="Object_26"
                  geometry={nodes.Object_26.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane012_24" position={[0.383, 0, -0.924]}>
                <mesh
                  name="Object_28"
                  geometry={nodes.Object_28.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane013_26" position={[-0.383, 0, 0.924]}>
                <mesh
                  name="Object_30"
                  geometry={nodes.Object_30.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane014_28" position={[-0.924, 0, -0.383]}>
                <mesh
                  name="Object_32"
                  geometry={nodes.Object_32.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane015_30" position={[0.924, 0, 0.383]}>
                <mesh
                  name="Object_34"
                  geometry={nodes.Object_34.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane016_32" position={[0.981, 0, -0.195]}>
                <mesh
                  name="Object_36"
                  geometry={nodes.Object_36.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane017_34" position={[-0.981, 0, 0.195]}>
                <mesh
                  name="Object_38"
                  geometry={nodes.Object_38.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane018_36" position={[-0.195, 0, -0.981]}>
                <mesh
                  name="Object_40"
                  geometry={nodes.Object_40.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane019_38" position={[0.195, 0, 0.981]}>
                <mesh
                  name="Object_42"
                  geometry={nodes.Object_42.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane020_40" position={[0.556, 0, -0.831]}>
                <mesh
                  name="Object_44"
                  geometry={nodes.Object_44.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane021_42" position={[-0.556, 0, 0.831]}>
                <mesh
                  name="Object_46"
                  geometry={nodes.Object_46.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane022_44" position={[-0.831, 0, -0.556]}>
                <mesh
                  name="Object_48"
                  geometry={nodes.Object_48.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane023_46" position={[0.831, 0, 0.556]}>
                <mesh
                  name="Object_50"
                  geometry={nodes.Object_50.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane024_48" position={[0.831, 0, -0.556]}>
                <mesh
                  name="Object_52"
                  geometry={nodes.Object_52.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane025_50" position={[-0.831, 0, 0.556]}>
                <mesh
                  name="Object_54"
                  geometry={nodes.Object_54.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane026_52" position={[-0.556, 0, -0.831]}>
                <mesh
                  name="Object_56"
                  geometry={nodes.Object_56.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane027_54" position={[0.556, 0, 0.831]}>
                <mesh
                  name="Object_58"
                  geometry={nodes.Object_58.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane028_56" position={[0.195, 0, -0.981]}>
                <mesh
                  name="Object_60"
                  geometry={nodes.Object_60.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane029_58" position={[-0.195, 0, 0.981]}>
                <mesh
                  name="Object_62"
                  geometry={nodes.Object_62.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane030_60" position={[-0.981, 0, -0.195]}>
                <mesh
                  name="Object_64"
                  geometry={nodes.Object_64.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane031_62" position={[0.981, 0, 0.195]}>
                <mesh
                  name="Object_66"
                  geometry={nodes.Object_66.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane032_64" position={[1, 2, 0]}>
                <mesh
                  name="Object_68"
                  geometry={nodes.Object_68.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane033_66" position={[-1, 2, 0]}>
                <mesh
                  name="Object_70"
                  geometry={nodes.Object_70.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane034_68" position={[0, 2, 1]}>
                <mesh
                  name="Object_72"
                  geometry={nodes.Object_72.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane035_70" position={[0, 2, -1]}>
                <mesh
                  name="Object_74"
                  geometry={nodes.Object_74.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane036_72" position={[0.707, 2, 0.707]}>
                <mesh
                  name="Object_76"
                  geometry={nodes.Object_76.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane037_74" position={[-0.707, 2, -0.707]}>
                <mesh
                  name="Object_78"
                  geometry={nodes.Object_78.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane038_76" position={[-0.707, 2, 0.707]}>
                <mesh
                  name="Object_80"
                  geometry={nodes.Object_80.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane039_78" position={[0.707, 2, -0.707]}>
                <mesh
                  name="Object_82"
                  geometry={nodes.Object_82.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane040_80" position={[0.924, 2, 0.383]}>
                <mesh
                  name="Object_84"
                  geometry={nodes.Object_84.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane041_82" position={[-0.924, 2, -0.383]}>
                <mesh
                  name="Object_86"
                  geometry={nodes.Object_86.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane042_84" position={[-0.383, 2, 0.924]}>
                <mesh
                  name="Object_88"
                  geometry={nodes.Object_88.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane043_86" position={[0.383, 2, -0.924]}>
                <mesh
                  name="Object_90"
                  geometry={nodes.Object_90.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane044_88" position={[0.383, 2, 0.924]}>
                <mesh
                  name="Object_92"
                  geometry={nodes.Object_92.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane045_90" position={[-0.383, 2, -0.924]}>
                <mesh
                  name="Object_94"
                  geometry={nodes.Object_94.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane046_92" position={[-0.924, 2, 0.383]}>
                <mesh
                  name="Object_96"
                  geometry={nodes.Object_96.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane047_94" position={[0.924, 2, -0.383]}>
                <mesh
                  name="Object_98"
                  geometry={nodes.Object_98.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane048_96" position={[0.981, 2, 0.195]}>
                <mesh
                  name="Object_100"
                  geometry={nodes.Object_100.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane049_98" position={[-0.981, 2, -0.195]}>
                <mesh
                  name="Object_102"
                  geometry={nodes.Object_102.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane050_100" position={[-0.195, 2, 0.981]}>
                <mesh
                  name="Object_104"
                  geometry={nodes.Object_104.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane051_102" position={[0.195, 2, -0.981]}>
                <mesh
                  name="Object_106"
                  geometry={nodes.Object_106.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane052_104" position={[0.556, 2, 0.831]}>
                <mesh
                  name="Object_108"
                  geometry={nodes.Object_108.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane053_106" position={[-0.556, 2, -0.831]}>
                <mesh
                  name="Object_110"
                  geometry={nodes.Object_110.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane054_108" position={[-0.831, 2, 0.556]}>
                <mesh
                  name="Object_112"
                  geometry={nodes.Object_112.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane055_110" position={[0.831, 2, -0.556]}>
                <mesh
                  name="Object_114"
                  geometry={nodes.Object_114.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane056_112" position={[0.831, 2, 0.556]}>
                <mesh
                  name="Object_116"
                  geometry={nodes.Object_116.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane057_114" position={[-0.831, 2, -0.556]}>
                <mesh
                  name="Object_118"
                  geometry={nodes.Object_118.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane058_116" position={[-0.556, 2, 0.831]}>
                <mesh
                  name="Object_120"
                  geometry={nodes.Object_120.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane059_118" position={[0.556, 2, -0.831]}>
                <mesh
                  name="Object_122"
                  geometry={nodes.Object_122.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane060_120" position={[0.195, 2, 0.981]}>
                <mesh
                  name="Object_124"
                  geometry={nodes.Object_124.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane061_122" position={[-0.195, 2, -0.981]}>
                <mesh
                  name="Object_126"
                  geometry={nodes.Object_126.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane062_124" position={[-0.981, 2, 0.195]}>
                <mesh
                  name="Object_128"
                  geometry={nodes.Object_128.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane063_126" position={[0.981, 2, -0.195]}>
                <mesh
                  name="Object_130"
                  geometry={nodes.Object_130.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane064_128" position={[1, -4, 0]}>
                <mesh
                  name="Object_132"
                  geometry={nodes.Object_132.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane065_130" position={[-1, -4, 0]}>
                <mesh
                  name="Object_134"
                  geometry={nodes.Object_134.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane066_132" position={[0, -4, -1]}>
                <mesh
                  name="Object_136"
                  geometry={nodes.Object_136.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane067_134" position={[0, -4, 1]}>
                <mesh
                  name="Object_138"
                  geometry={nodes.Object_138.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane068_136" position={[0.707, -4, -0.707]}>
                <mesh
                  name="Object_140"
                  geometry={nodes.Object_140.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane069_138" position={[-0.707, -4, 0.707]}>
                <mesh
                  name="Object_142"
                  geometry={nodes.Object_142.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane070_140" position={[-0.707, -4, -0.707]}>
                <mesh
                  name="Object_144"
                  geometry={nodes.Object_144.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane071_142" position={[0.707, -4, 0.707]}>
                <mesh
                  name="Object_146"
                  geometry={nodes.Object_146.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane072_144" position={[0.924, -4, -0.383]}>
                <mesh
                  name="Object_148"
                  geometry={nodes.Object_148.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane073_146" position={[-0.924, -4, 0.383]}>
                <mesh
                  name="Object_150"
                  geometry={nodes.Object_150.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane074_148" position={[-0.383, -4, -0.924]}>
                <mesh
                  name="Object_152"
                  geometry={nodes.Object_152.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane075_150" position={[0.383, -4, 0.924]}>
                <mesh
                  name="Object_154"
                  geometry={nodes.Object_154.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane076_152" position={[0.383, -4, -0.924]}>
                <mesh
                  name="Object_156"
                  geometry={nodes.Object_156.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane077_154" position={[-0.383, -4, 0.924]}>
                <mesh
                  name="Object_158"
                  geometry={nodes.Object_158.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane078_156" position={[-0.924, -4, -0.383]}>
                <mesh
                  name="Object_160"
                  geometry={nodes.Object_160.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane079_158" position={[0.924, -4, 0.383]}>
                <mesh
                  name="Object_162"
                  geometry={nodes.Object_162.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane080_160" position={[0.981, -4, -0.195]}>
                <mesh
                  name="Object_164"
                  geometry={nodes.Object_164.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane081_162" position={[-0.981, -4, 0.195]}>
                <mesh
                  name="Object_166"
                  geometry={nodes.Object_166.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane082_164" position={[-0.195, -4, -0.981]}>
                <mesh
                  name="Object_168"
                  geometry={nodes.Object_168.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane083_166" position={[0.195, -4, 0.981]}>
                <mesh
                  name="Object_170"
                  geometry={nodes.Object_170.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane084_168" position={[0.556, -4, -0.831]}>
                <mesh
                  name="Object_172"
                  geometry={nodes.Object_172.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane085_170" position={[-0.556, -4, 0.831]}>
                <mesh
                  name="Object_174"
                  geometry={nodes.Object_174.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane086_172" position={[-0.831, -4, -0.556]}>
                <mesh
                  name="Object_176"
                  geometry={nodes.Object_176.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane087_174" position={[0.831, -4, 0.556]}>
                <mesh
                  name="Object_178"
                  geometry={nodes.Object_178.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane088_176" position={[0.831, -4, -0.556]}>
                <mesh
                  name="Object_180"
                  geometry={nodes.Object_180.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane089_178" position={[-0.831, -4, 0.556]}>
                <mesh
                  name="Object_182"
                  geometry={nodes.Object_182.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane090_180" position={[-0.556, -4, -0.831]}>
                <mesh
                  name="Object_184"
                  geometry={nodes.Object_184.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane091_182" position={[0.556, -4, 0.831]}>
                <mesh
                  name="Object_186"
                  geometry={nodes.Object_186.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane092_184" position={[0.195, -4, -0.981]}>
                <mesh
                  name="Object_188"
                  geometry={nodes.Object_188.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane093_186" position={[-0.195, -4, 0.981]}>
                <mesh
                  name="Object_190"
                  geometry={nodes.Object_190.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane094_188" position={[-0.981, -4, -0.195]}>
                <mesh
                  name="Object_192"
                  geometry={nodes.Object_192.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane095_190" position={[0.981, -4, 0.195]}>
                <mesh
                  name="Object_194"
                  geometry={nodes.Object_194.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane096_192" position={[1, -2, 0]}>
                <mesh
                  name="Object_196"
                  geometry={nodes.Object_196.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane097_194" position={[-1, -2, 0]}>
                <mesh
                  name="Object_198"
                  geometry={nodes.Object_198.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane098_196" position={[0, -2, 1]}>
                <mesh
                  name="Object_200"
                  geometry={nodes.Object_200.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane099_198" position={[0, -2, -1]}>
                <mesh
                  name="Object_202"
                  geometry={nodes.Object_202.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane100_200" position={[0.707, -2, 0.707]}>
                <mesh
                  name="Object_204"
                  geometry={nodes.Object_204.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane101_202" position={[-0.707, -2, -0.707]}>
                <mesh
                  name="Object_206"
                  geometry={nodes.Object_206.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane102_204" position={[-0.707, -2, 0.707]}>
                <mesh
                  name="Object_208"
                  geometry={nodes.Object_208.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane103_206" position={[0.707, -2, -0.707]}>
                <mesh
                  name="Object_210"
                  geometry={nodes.Object_210.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane104_208" position={[0.924, -2, 0.383]}>
                <mesh
                  name="Object_212"
                  geometry={nodes.Object_212.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane105_210" position={[-0.924, -2, -0.383]}>
                <mesh
                  name="Object_214"
                  geometry={nodes.Object_214.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane106_212" position={[-0.383, -2, 0.924]}>
                <mesh
                  name="Object_216"
                  geometry={nodes.Object_216.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane107_214" position={[0.383, -2, -0.924]}>
                <mesh
                  name="Object_218"
                  geometry={nodes.Object_218.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane108_216" position={[0.383, -2, 0.924]}>
                <mesh
                  name="Object_220"
                  geometry={nodes.Object_220.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane109_218" position={[-0.383, -2, -0.924]}>
                <mesh
                  name="Object_222"
                  geometry={nodes.Object_222.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane110_220" position={[-0.924, -2, 0.383]}>
                <mesh
                  name="Object_224"
                  geometry={nodes.Object_224.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane111_222" position={[0.924, -2, -0.383]}>
                <mesh
                  name="Object_226"
                  geometry={nodes.Object_226.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane112_224" position={[0.981, -2, 0.195]}>
                <mesh
                  name="Object_228"
                  geometry={nodes.Object_228.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane113_226" position={[-0.981, -2, -0.195]}>
                <mesh
                  name="Object_230"
                  geometry={nodes.Object_230.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane114_228" position={[-0.195, -2, 0.981]}>
                <mesh
                  name="Object_232"
                  geometry={nodes.Object_232.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane115_230" position={[0.195, -2, -0.981]}>
                <mesh
                  name="Object_234"
                  geometry={nodes.Object_234.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane116_232" position={[0.556, -2, 0.831]}>
                <mesh
                  name="Object_236"
                  geometry={nodes.Object_236.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane117_234" position={[-0.556, -2, -0.831]}>
                <mesh
                  name="Object_238"
                  geometry={nodes.Object_238.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane118_236" position={[-0.831, -2, 0.556]}>
                <mesh
                  name="Object_240"
                  geometry={nodes.Object_240.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane119_238" position={[0.831, -2, -0.556]}>
                <mesh
                  name="Object_242"
                  geometry={nodes.Object_242.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane120_240" position={[0.831, -2, 0.556]}>
                <mesh
                  name="Object_244"
                  geometry={nodes.Object_244.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane121_242" position={[-0.831, -2, -0.556]}>
                <mesh
                  name="Object_246"
                  geometry={nodes.Object_246.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane122_244" position={[-0.556, -2, 0.831]}>
                <mesh
                  name="Object_248"
                  geometry={nodes.Object_248.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane123_246" position={[0.556, -2, -0.831]}>
                <mesh
                  name="Object_250"
                  geometry={nodes.Object_250.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane124_248" position={[0.195, -2, 0.981]}>
                <mesh
                  name="Object_252"
                  geometry={nodes.Object_252.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane125_250" position={[-0.195, -2, -0.981]}>
                <mesh
                  name="Object_254"
                  geometry={nodes.Object_254.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane126_252" position={[-0.981, -2, 0.195]}>
                <mesh
                  name="Object_256"
                  geometry={nodes.Object_256.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane127_254" position={[0.981, -2, -0.195]}>
                <mesh
                  name="Object_258"
                  geometry={nodes.Object_258.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane128_256" position={[1, -8, 0]}>
                <mesh
                  name="Object_260"
                  geometry={nodes.Object_260.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane129_258" position={[-1, -8, 0]}>
                <mesh
                  name="Object_262"
                  geometry={nodes.Object_262.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane130_260" position={[0, -8, -1]}>
                <mesh
                  name="Object_264"
                  geometry={nodes.Object_264.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane131_262" position={[0, -8, 1]}>
                <mesh
                  name="Object_266"
                  geometry={nodes.Object_266.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane132_264" position={[0.707, -8, -0.707]}>
                <mesh
                  name="Object_268"
                  geometry={nodes.Object_268.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane133_266" position={[-0.707, -8, 0.707]}>
                <mesh
                  name="Object_270"
                  geometry={nodes.Object_270.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane134_268" position={[-0.707, -8, -0.707]}>
                <mesh
                  name="Object_272"
                  geometry={nodes.Object_272.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane135_270" position={[0.707, -8, 0.707]}>
                <mesh
                  name="Object_274"
                  geometry={nodes.Object_274.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane136_272" position={[0.924, -8, -0.383]}>
                <mesh
                  name="Object_276"
                  geometry={nodes.Object_276.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane137_274" position={[-0.924, -8, 0.383]}>
                <mesh
                  name="Object_278"
                  geometry={nodes.Object_278.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane138_276" position={[-0.383, -8, -0.924]}>
                <mesh
                  name="Object_280"
                  geometry={nodes.Object_280.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane139_278" position={[0.383, -8, 0.924]}>
                <mesh
                  name="Object_282"
                  geometry={nodes.Object_282.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane140_280" position={[0.383, -8, -0.924]}>
                <mesh
                  name="Object_284"
                  geometry={nodes.Object_284.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane141_282" position={[-0.383, -8, 0.924]}>
                <mesh
                  name="Object_286"
                  geometry={nodes.Object_286.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane142_284" position={[-0.924, -8, -0.383]}>
                <mesh
                  name="Object_288"
                  geometry={nodes.Object_288.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane143_286" position={[0.924, -8, 0.383]}>
                <mesh
                  name="Object_290"
                  geometry={nodes.Object_290.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane144_288" position={[0.981, -8, -0.195]}>
                <mesh
                  name="Object_292"
                  geometry={nodes.Object_292.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane145_290" position={[-0.981, -8, 0.195]}>
                <mesh
                  name="Object_294"
                  geometry={nodes.Object_294.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane146_292" position={[-0.195, -8, -0.981]}>
                <mesh
                  name="Object_296"
                  geometry={nodes.Object_296.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane147_294" position={[0.195, -8, 0.981]}>
                <mesh
                  name="Object_298"
                  geometry={nodes.Object_298.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane148_296" position={[0.556, -8, -0.831]}>
                <mesh
                  name="Object_300"
                  geometry={nodes.Object_300.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane149_298" position={[-0.556, -8, 0.831]}>
                <mesh
                  name="Object_302"
                  geometry={nodes.Object_302.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane150_300" position={[-0.831, -8, -0.556]}>
                <mesh
                  name="Object_304"
                  geometry={nodes.Object_304.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane151_302" position={[0.831, -8, 0.556]}>
                <mesh
                  name="Object_306"
                  geometry={nodes.Object_306.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane152_304" position={[0.831, -8, -0.556]}>
                <mesh
                  name="Object_308"
                  geometry={nodes.Object_308.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane153_306" position={[-0.831, -8, 0.556]}>
                <mesh
                  name="Object_310"
                  geometry={nodes.Object_310.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane154_308" position={[-0.556, -8, -0.831]}>
                <mesh
                  name="Object_312"
                  geometry={nodes.Object_312.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane155_310" position={[0.556, -8, 0.831]}>
                <mesh
                  name="Object_314"
                  geometry={nodes.Object_314.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane156_312" position={[0.195, -8, -0.981]}>
                <mesh
                  name="Object_316"
                  geometry={nodes.Object_316.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane157_314" position={[-0.195, -8, 0.981]}>
                <mesh
                  name="Object_318"
                  geometry={nodes.Object_318.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane158_316" position={[-0.981, -8, -0.195]}>
                <mesh
                  name="Object_320"
                  geometry={nodes.Object_320.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane159_318" position={[0.981, -8, 0.195]}>
                <mesh
                  name="Object_322"
                  geometry={nodes.Object_322.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane160_320" position={[1, -6, 0]}>
                <mesh
                  name="Object_324"
                  geometry={nodes.Object_324.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane161_322" position={[-1, -6, 0]}>
                <mesh
                  name="Object_326"
                  geometry={nodes.Object_326.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane162_324" position={[0, -6, 1]}>
                <mesh
                  name="Object_328"
                  geometry={nodes.Object_328.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane163_326" position={[0, -6, -1]}>
                <mesh
                  name="Object_330"
                  geometry={nodes.Object_330.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane164_328" position={[0.707, -6, 0.707]}>
                <mesh
                  name="Object_332"
                  geometry={nodes.Object_332.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane165_330" position={[-0.707, -6, -0.707]}>
                <mesh
                  name="Object_334"
                  geometry={nodes.Object_334.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane166_332" position={[-0.707, -6, 0.707]}>
                <mesh
                  name="Object_336"
                  geometry={nodes.Object_336.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane167_334" position={[0.707, -6, -0.707]}>
                <mesh
                  name="Object_338"
                  geometry={nodes.Object_338.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane168_336" position={[0.924, -6, 0.383]}>
                <mesh
                  name="Object_340"
                  geometry={nodes.Object_340.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane169_338" position={[-0.924, -6, -0.383]}>
                <mesh
                  name="Object_342"
                  geometry={nodes.Object_342.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane170_340" position={[-0.383, -6, 0.924]}>
                <mesh
                  name="Object_344"
                  geometry={nodes.Object_344.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane171_342" position={[0.383, -6, -0.924]}>
                <mesh
                  name="Object_346"
                  geometry={nodes.Object_346.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane172_344" position={[0.383, -6, 0.924]}>
                <mesh
                  name="Object_348"
                  geometry={nodes.Object_348.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane173_346" position={[-0.383, -6, -0.924]}>
                <mesh
                  name="Object_350"
                  geometry={nodes.Object_350.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane174_348" position={[-0.924, -6, 0.383]}>
                <mesh
                  name="Object_352"
                  geometry={nodes.Object_352.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane175_350" position={[0.924, -6, -0.383]}>
                <mesh
                  name="Object_354"
                  geometry={nodes.Object_354.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane176_352" position={[0.981, -6, 0.195]}>
                <mesh
                  name="Object_356"
                  geometry={nodes.Object_356.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane177_354" position={[-0.981, -6, -0.195]}>
                <mesh
                  name="Object_358"
                  geometry={nodes.Object_358.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane178_356" position={[-0.195, -6, 0.981]}>
                <mesh
                  name="Object_360"
                  geometry={nodes.Object_360.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane179_358" position={[0.195, -6, -0.981]}>
                <mesh
                  name="Object_362"
                  geometry={nodes.Object_362.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane180_360" position={[0.556, -6, 0.831]}>
                <mesh
                  name="Object_364"
                  geometry={nodes.Object_364.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane181_362" position={[-0.556, -6, -0.831]}>
                <mesh
                  name="Object_366"
                  geometry={nodes.Object_366.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane182_364" position={[-0.831, -6, 0.556]}>
                <mesh
                  name="Object_368"
                  geometry={nodes.Object_368.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane183_366" position={[0.831, -6, -0.556]}>
                <mesh
                  name="Object_370"
                  geometry={nodes.Object_370.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane184_368" position={[0.831, -6, 0.556]}>
                <mesh
                  name="Object_372"
                  geometry={nodes.Object_372.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane185_370" position={[-0.831, -6, -0.556]}>
                <mesh
                  name="Object_374"
                  geometry={nodes.Object_374.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane186_372" position={[-0.556, -6, 0.831]}>
                <mesh
                  name="Object_376"
                  geometry={nodes.Object_376.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane187_374" position={[0.556, -6, -0.831]}>
                <mesh
                  name="Object_378"
                  geometry={nodes.Object_378.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane188_376" position={[0.195, -6, 0.981]}>
                <mesh
                  name="Object_380"
                  geometry={nodes.Object_380.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane189_378" position={[-0.195, -6, -0.981]}>
                <mesh
                  name="Object_382"
                  geometry={nodes.Object_382.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane190_380" position={[-0.981, -6, 0.195]}>
                <mesh
                  name="Object_384"
                  geometry={nodes.Object_384.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane191_382" position={[0.981, -6, -0.195]}>
                <mesh
                  name="Object_386"
                  geometry={nodes.Object_386.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane192_384" position={[1, -12, 0]}>
                <mesh
                  name="Object_388"
                  geometry={nodes.Object_388.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane193_386" position={[-1, -12, 0]}>
                <mesh
                  name="Object_390"
                  geometry={nodes.Object_390.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane194_388" position={[0, -12, -1]}>
                <mesh
                  name="Object_392"
                  geometry={nodes.Object_392.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane195_390" position={[0, -12, 1]}>
                <mesh
                  name="Object_394"
                  geometry={nodes.Object_394.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane196_392" position={[0.707, -12, -0.707]}>
                <mesh
                  name="Object_396"
                  geometry={nodes.Object_396.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane197_394" position={[-0.707, -12, 0.707]}>
                <mesh
                  name="Object_398"
                  geometry={nodes.Object_398.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane198_396" position={[-0.707, -12, -0.707]}>
                <mesh
                  name="Object_400"
                  geometry={nodes.Object_400.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane199_398" position={[0.707, -12, 0.707]}>
                <mesh
                  name="Object_402"
                  geometry={nodes.Object_402.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane200_400" position={[0.924, -12, -0.383]}>
                <mesh
                  name="Object_404"
                  geometry={nodes.Object_404.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane201_402" position={[-0.924, -12, 0.383]}>
                <mesh
                  name="Object_406"
                  geometry={nodes.Object_406.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane202_404" position={[-0.383, -12, -0.924]}>
                <mesh
                  name="Object_408"
                  geometry={nodes.Object_408.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane203_406" position={[0.383, -12, 0.924]}>
                <mesh
                  name="Object_410"
                  geometry={nodes.Object_410.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane204_408" position={[0.383, -12, -0.924]}>
                <mesh
                  name="Object_412"
                  geometry={nodes.Object_412.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane205_410" position={[-0.383, -12, 0.924]}>
                <mesh
                  name="Object_414"
                  geometry={nodes.Object_414.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane206_412" position={[-0.924, -12, -0.383]}>
                <mesh
                  name="Object_416"
                  geometry={nodes.Object_416.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane207_414" position={[0.924, -12, 0.383]}>
                <mesh
                  name="Object_418"
                  geometry={nodes.Object_418.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane208_416" position={[0.981, -12, -0.195]}>
                <mesh
                  name="Object_420"
                  geometry={nodes.Object_420.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane209_418" position={[-0.981, -12, 0.195]}>
                <mesh
                  name="Object_422"
                  geometry={nodes.Object_422.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane210_420" position={[-0.195, -12, -0.981]}>
                <mesh
                  name="Object_424"
                  geometry={nodes.Object_424.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane211_422" position={[0.195, -12, 0.981]}>
                <mesh
                  name="Object_426"
                  geometry={nodes.Object_426.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane212_424" position={[0.556, -12, -0.831]}>
                <mesh
                  name="Object_428"
                  geometry={nodes.Object_428.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane213_426" position={[-0.556, -12, 0.831]}>
                <mesh
                  name="Object_430"
                  geometry={nodes.Object_430.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane214_428" position={[-0.831, -12, -0.556]}>
                <mesh
                  name="Object_432"
                  geometry={nodes.Object_432.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane215_430" position={[0.831, -12, 0.556]}>
                <mesh
                  name="Object_434"
                  geometry={nodes.Object_434.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane216_432" position={[0.831, -12, -0.556]}>
                <mesh
                  name="Object_436"
                  geometry={nodes.Object_436.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane217_434" position={[-0.831, -12, 0.556]}>
                <mesh
                  name="Object_438"
                  geometry={nodes.Object_438.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane218_436" position={[-0.556, -12, -0.831]}>
                <mesh
                  name="Object_440"
                  geometry={nodes.Object_440.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane219_438" position={[0.556, -12, 0.831]}>
                <mesh
                  name="Object_442"
                  geometry={nodes.Object_442.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane220_440" position={[0.195, -12, -0.981]}>
                <mesh
                  name="Object_444"
                  geometry={nodes.Object_444.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane221_442" position={[-0.195, -12, 0.981]}>
                <mesh
                  name="Object_446"
                  geometry={nodes.Object_446.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane222_444" position={[-0.981, -12, -0.195]}>
                <mesh
                  name="Object_448"
                  geometry={nodes.Object_448.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane223_446" position={[0.981, -12, 0.195]}>
                <mesh
                  name="Object_450"
                  geometry={nodes.Object_450.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane224_448" position={[1, -10, 0]}>
                <mesh
                  name="Object_452"
                  geometry={nodes.Object_452.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane225_450" position={[-1, -10, 0]}>
                <mesh
                  name="Object_454"
                  geometry={nodes.Object_454.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane226_452" position={[0, -10, 1]}>
                <mesh
                  name="Object_456"
                  geometry={nodes.Object_456.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane227_454" position={[0, -10, -1]}>
                <mesh
                  name="Object_458"
                  geometry={nodes.Object_458.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane228_456" position={[0.707, -10, 0.707]}>
                <mesh
                  name="Object_460"
                  geometry={nodes.Object_460.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane229_458" position={[-0.707, -10, -0.707]}>
                <mesh
                  name="Object_462"
                  geometry={nodes.Object_462.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane230_460" position={[-0.707, -10, 0.707]}>
                <mesh
                  name="Object_464"
                  geometry={nodes.Object_464.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane231_462" position={[0.707, -10, -0.707]}>
                <mesh
                  name="Object_466"
                  geometry={nodes.Object_466.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane232_464" position={[0.924, -10, 0.383]}>
                <mesh
                  name="Object_468"
                  geometry={nodes.Object_468.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane233_466" position={[-0.924, -10, -0.383]}>
                <mesh
                  name="Object_470"
                  geometry={nodes.Object_470.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane234_468" position={[-0.383, -10, 0.924]}>
                <mesh
                  name="Object_472"
                  geometry={nodes.Object_472.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane235_470" position={[0.383, -10, -0.924]}>
                <mesh
                  name="Object_474"
                  geometry={nodes.Object_474.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane236_472" position={[0.383, -10, 0.924]}>
                <mesh
                  name="Object_476"
                  geometry={nodes.Object_476.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane237_474" position={[-0.383, -10, -0.924]}>
                <mesh
                  name="Object_478"
                  geometry={nodes.Object_478.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane238_476" position={[-0.924, -10, 0.383]}>
                <mesh
                  name="Object_480"
                  geometry={nodes.Object_480.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane239_478" position={[0.924, -10, -0.383]}>
                <mesh
                  name="Object_482"
                  geometry={nodes.Object_482.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane240_480" position={[0.981, -10, 0.195]}>
                <mesh
                  name="Object_484"
                  geometry={nodes.Object_484.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane241_482" position={[-0.981, -10, -0.195]}>
                <mesh
                  name="Object_486"
                  geometry={nodes.Object_486.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane242_484" position={[-0.195, -10, 0.981]}>
                <mesh
                  name="Object_488"
                  geometry={nodes.Object_488.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane243_486" position={[0.195, -10, -0.981]}>
                <mesh
                  name="Object_490"
                  geometry={nodes.Object_490.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane244_488" position={[0.556, -10, 0.831]}>
                <mesh
                  name="Object_492"
                  geometry={nodes.Object_492.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane245_490" position={[-0.556, -10, -0.831]}>
                <mesh
                  name="Object_494"
                  geometry={nodes.Object_494.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane246_492" position={[-0.831, -10, 0.556]}>
                <mesh
                  name="Object_496"
                  geometry={nodes.Object_496.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane247_494" position={[0.831, -10, -0.556]}>
                <mesh
                  name="Object_498"
                  geometry={nodes.Object_498.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane248_496" position={[0.831, -10, 0.556]}>
                <mesh
                  name="Object_500"
                  geometry={nodes.Object_500.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane249_498" position={[-0.831, -10, -0.556]}>
                <mesh
                  name="Object_502"
                  geometry={nodes.Object_502.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane250_500" position={[-0.556, -10, 0.831]}>
                <mesh
                  name="Object_504"
                  geometry={nodes.Object_504.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane251_502" position={[0.556, -10, -0.831]}>
                <mesh
                  name="Object_506"
                  geometry={nodes.Object_506.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane252_504" position={[0.195, -10, 0.981]}>
                <mesh
                  name="Object_508"
                  geometry={nodes.Object_508.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane253_506" position={[-0.195, -10, -0.981]}>
                <mesh
                  name="Object_510"
                  geometry={nodes.Object_510.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane254_508" position={[-0.981, -10, 0.195]}>
                <mesh
                  name="Object_512"
                  geometry={nodes.Object_512.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Plane255_510" position={[0.981, -10, -0.195]}>
                <mesh
                  name="Object_514"
                  geometry={nodes.Object_514.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/pulse.glb");
