/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/rampaging_t_rex.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function RampagingTRex(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/rampaging_t_rex.glb"
  );
  const { actions, mixer } = useAnimations(animations, group);

  useEffect(() => {
    const action = actions["run"];
    action.play();
  }, [actions, mixer]);

  console.log(actions);
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="RootNode0" scale={0.01}>
          <group name="geo1">
            <skinnedMesh
              name="TRex2"
              geometry={nodes.TRex2.geometry}
              material={nodes.TRex2.material}
              skeleton={nodes.TRex2.skeleton}
            />
          </group>
          <group name="skeletal3">
            <primitive object={nodes.bn_Spine4} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/rampaging_t_rex.glb");
