/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/shadow_dragon.glb 
Author: HallowDragon (https://sketchfab.com/HallowDragon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shadow-dragon-a5e537f7365a4c74b41fa521676ae1cd
Title: Shadow Dragon
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function ShadowDragon(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/shadow_dragon.glb");
  const { actions, mixer } = useAnimations(animations, group);

  useEffect(() => {
    // Attack, Die, Fire While Flying, Hover, Hurt, Idle, Run, Start Flying
    actions["Hover"].play();
    mixer.timeScale = 0.5;
  }, [actions, mixer]);

  console.log(actions);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sketchfab_model_0" rotation={[-Math.PI / 2, 0, 0]}>
                <group
                  name="npc_mst_228fbx_1"
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.1}
                >
                  <group name="Object_2_2">
                    <group name="RootNode_3">
                      <group name="npc_mst_228_4">
                        <group
                          name="Mesh_Shadow_5"
                          position={[0, 0.05, 0]}
                          rotation={[-Math.PI / 2, 0, 0]}
                        >
                          <group name="Mesh_Shadow_Shadow_Material_0_6">
                            <mesh
                              name="Object_10"
                              geometry={nodes.Object_10.geometry}
                              material={materials.Shadow_Material}
                            />
                          </group>
                        </group>
                        <group
                          name="BoneRoot_7"
                          rotation={[-Math.PI / 2, 0, 0]}
                        >
                          <group name="Object_8_8">
                            <group name="GLTF_created_0">
                              <primitive
                                object={nodes.GLTF_created_0_rootJoint}
                              />
                              <group name="Object_86_86_correction">
                                <group name="Object_86_86" />
                              </group>
                              <skinnedMesh
                                name="Object_101"
                                geometry={nodes.Object_101.geometry}
                                material={materials.mat_npc_mst_228}
                                skeleton={nodes.Object_101.skeleton}
                              />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/shadow_dragon.glb");
