/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/high/sofa.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Sofa(props) {
  const { nodes, materials } = useGLTF('/models/high/sofa.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.chesterfield_style_sofa_1.geometry} material={materials.upholstery_Mat} />
        <mesh geometry={nodes.chesterfield_style_sofa_2.geometry} material={materials.pins_Mat} />
        <mesh geometry={nodes.chesterfield_style_sofa_3.geometry} material={materials.legs_Mat} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/high/sofa.glb')
