/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/solar_system_real_scale_2k_textures.glb
Author: FyorDev (https://sketchfab.com/FyorDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/solar-system-real-scale-2k-textures-febde2b6e3f64b06965620fd3ddc97c2
Title: Solar system [REAL SCALE] 2k textures
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/solar_system_real_scale_2k_textures.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Earth} rotation={[-Math.PI, 0.15, -Math.PI]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Venus} position={[0, 0, 3]} rotation={[0, -1.04, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Mercury} position={[0, 0, 6]} rotation={[0, -1.04, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Mars} position={[0, 0, -3]} rotation={[0, -1.04, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Jupiter} position={[0, 0, -30]} rotation={[0, -1.04, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Saturn} position={[0, 0, -50]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Uranus} position={[0, 0, -70]} rotation={[0, -1.04, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Neptune} position={[0, 0, -80]} rotation={[0, -1.04, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.material} position={[0, 0, 200]} rotation={[0, -1.04, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.moon} position={[-2, 0, 0]} rotation={[0, -1.04, 0]} scale={0.12} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.ceres} position={[0, 0, -9]} rotation={[0, -1.04, 0]} scale={0.03} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.eris} position={[0, 0, -90]} rotation={[0, -1.04, 0]} scale={0.07} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.haumea} position={[0, 0, -84]} rotation={[0, -1.04, 0]} scale={0.05} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.makemake} position={[0, 0, -87]} rotation={[0, -1.04, 0]} scale={0.05} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.SaturnRing} position={[0, 0, -50]} />
      {/* <mesh geometry={nodes.Object_34.geometry} material={materials.Environment} scale={1000} /> */}
    </group>
  )
}

useGLTF.preload('/models/solar_system_real_scale_2k_textures.glb')
