/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/space_ship.glb -r public
Author: Pump (https://sketchfab.com/Pump)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-ship-70f79932121d47ac998aeec03ede6e3c
Title: Space Ship
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Spacecraft(props) {
  const { nodes, materials } = useGLTF("/models/space_ship.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.00005}>
        <group position={[-9589.74, -11905.78, -6412.2]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.blanco} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.motores} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.sensores} />
          {/* <mesh geometry={nodes.Object_6.geometry} material={materials.sensores_1} /> */}
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/space_ship.glb");
