/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/spider_white_anim.glb 
Author: creator830 (https://sketchfab.com/1223shanae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spider-b500d95f0c6f453f8bd308a6c7417179
Title: Spider
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function SpiderWhiteAnim(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/spider_white_anim.glb')
  const { actions, mixer } = useAnimations(animations, group)
  
  // Armature.001|Walk
  useEffect(() => {
    actions["Armature.001|Walk"].play();
    mixer.timeScale = 1;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={32.861}>
          <group name="34565e28b07749f9967cdce81b43cf4cfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Light" position={[12.229, 17.712, -3.016]} rotation={[1.89, 0.881, -2.045]} scale={3}>
                  <group name="Object_5" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_6" />
                  </group>
                </group>
                <group name="Camera" position={[22.077, 14.875, 20.777]} rotation={[-Math.PI, 0.756, 2.68]} scale={3}>
                  <group name="Object_8" />
                </group>
                <group name="RootNode_(gltf_orientation_matrix)" rotation={[-Math.PI / 2, 0, 0]} scale={3}>
                  <group name="RootNode_(model_correction_matrix)" scale={0.806}>
                    <group name="b5d46d444dbb471e81c9e32da44a36c4fbx" rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Node_3">
                        <group name="RootNode_1">
                          <group name="Spider" />
                          <group name="Armature" rotation={[-Math.PI / 2, 0, 0]}>
                            <group name="Armature001">
                              <group name="Object_17">
                                <primitive object={nodes._rootJoint} />
                                <group name="Node_9" />
                                <group name="Object_186" rotation={[-Math.PI / 2, 0, 0]} scale={2.419} />
                                <group name="Object_188" rotation={[-Math.PI / 2, 0, 0]} scale={2.419} />
                                <skinnedMesh name="Object_187" geometry={nodes.Object_187.geometry} material={materials.spider_Mat} skeleton={nodes.Object_187.skeleton} />
                                <skinnedMesh name="Object_189" geometry={nodes.Object_189.geometry} material={materials.Eyes} skeleton={nodes.Object_189.skeleton} />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="Spider_spider_Mat_0" rotation={[-Math.PI / 2, 0, 0]} scale={2.419} />
                <group name="Spider_Eyes_0" rotation={[-Math.PI / 2, 0, 0]} scale={2.419} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/spider_white_anim.glb')
