/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/spider.glb 
Author: JoshTrevisiol (https://sketchfab.com/JoshTrevisiol)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spider-bc0a750b8363472e80eaa5881655ed23
Title: Spider
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Spider(props) {
  const { nodes, materials } = useGLTF('/models/spider.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -19.917, 59.021]} rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.blinn4SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert3SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/spider.glb')
