/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/spider_ugly_anim.glb 
Author: maksroberthut (https://sketchfab.com/maksroberthut)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spider-with-animation-ba8149ca471a4708bfdba07460450815
Title: Spider with Animation
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function SpiderUglyAnim(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/spider_ugly_anim.glb')
  const { actions, mixer } = useAnimations(animations, group)

  useEffect(() => {
    actions["Spider_default.005"].play();
    mixer.timeScale = 1;
  });
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="root_64">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="Spiderbody_low_62" />
                  <group name="Spidereyes_low_63" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['Mat_Spiderbody.001']} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['MAT_Spider_eyes.001']} skeleton={nodes.Object_9.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/spider_ugly_anim.glb')
