/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/spider_hifi_anim.glb 
Author: jonmariano21 (https://sketchfab.com/jonmariano21)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hi-fi-spider-ff8a4433a5d449a3a0fc54989185a024
Title: hi-fi-spider
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function SpiderHifiAnim(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/spider_hifi_anim.glb')
  const { actions, mixer } = useAnimations(animations, group)
  
  // actions = CircleAction, walk cycle
  useEffect(() => {
    actions["walk cycle"].play();
    mixer.timeScale = 1;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="RootNode_(gltf_orientation_matrix)_0" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="RootNode_(model_correction_matrix)_1">
                  <group name="root_2">
                    <group name="GLTF_SceneRootNode_3" rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Circle_84_90" />
                      <group name="spider_armature_83_4" position={[0, 6.267, 0]}>
                        <group name="GLTF_created_0_5">
                          <group name="GLTF_created_0">
                            <primitive object={nodes.GLTF_created_0_rootJoint} />
                            <group name="_8" />
                            <group name="_9" />
                            <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Default} skeleton={nodes.Object_12.skeleton} />
                            <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.material_0} skeleton={nodes.Object_14.skeleton} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/spider_hifi_anim.glb')
