/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/temple_of_light.glb 
Author: Miguelangelo Rosario (https://sketchfab.com/miguelangelo2k)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/temple-of-light-infinite-mandalas-720acbe09c84432a8f6712a0b685e1be
Title: Temple of Light (infinite mandalas)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function TempleOfLight(props) {
  const { nodes, materials } = useGLTF("/models/temple_of_light.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, 0]} scale={0.00001}>
        <group position={[-197000, -169227.266, -197000]}>
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials["24___Default"]}
          />
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial1}
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial10}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial11}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial16}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial17}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial2}
          />
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial20}
          />
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial21}
          />
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial3}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial5}
          />
          <mesh
            geometry={nodes.Object_14.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial8}
          />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={materials.wire_088199225}
          />
          <mesh
            geometry={nodes.Object_16.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial12}
          />
          <mesh
            geometry={nodes.Object_17.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial13}
          />
          <mesh
            geometry={nodes.Object_18.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial13}
          />
          <mesh
            geometry={nodes.Object_19.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial13}
          />
          <mesh
            geometry={nodes.Object_20.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial13}
          />
          <mesh
            geometry={nodes.Object_21.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial13}
          />
          <mesh
            geometry={nodes.Object_22.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial13}
          />
          <mesh
            geometry={nodes.Object_23.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial13}
          />
          <mesh
            geometry={nodes.Object_24.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial14}
          />
          <mesh
            geometry={nodes.Object_25.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial14}
          />
          <mesh
            geometry={nodes.Object_26.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial15}
          />
          <mesh
            geometry={nodes.Object_27.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial15}
          />
          <mesh
            geometry={nodes.Object_28.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial18}
          />
          <mesh
            geometry={nodes.Object_29.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial19}
          />
          <mesh
            geometry={nodes.Object_30.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial22}
          />
          <mesh
            geometry={nodes.Object_31.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial22}
          />
          <mesh
            geometry={nodes.Object_32.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial22}
          />
          <mesh
            geometry={nodes.Object_33.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial22}
          />
          <mesh
            geometry={nodes.Object_34.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial22}
          />
          <mesh
            geometry={nodes.Object_35.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial4}
          />
          <mesh
            geometry={nodes.Object_36.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial6}
          />
          <mesh
            geometry={nodes.Object_37.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial7}
          />
          <mesh
            geometry={nodes.Object_38.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial9}
          />
          <mesh
            geometry={nodes.Object_39.geometry}
            material={materials.GravitySketch_14_30_33BaseMaterial9}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/temple_of_light.glb");
