/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/the_great_morpheus.glb 
Author: tamminen (https://sketchfab.com/tamminen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-great-morpheus-5547c76fdb1844ea97cfd876928f13cb
Title: The Great Morpheus
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function TheGreatMorpheus(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/the_great_morpheus.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sphere_0" position={[-1.5, 0, 0]}>
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Sphere001_2" position={[1.5, 0, 0]}>
                <mesh
                  name="Object_6"
                  geometry={nodes.Object_6.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Sphere002_4" position={[0, 1.5, 0]}>
                <mesh
                  name="Object_8"
                  geometry={nodes.Object_8.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Sphere003_6" position={[0, -1.5, 0]}>
                <mesh
                  name="Object_10"
                  geometry={nodes.Object_10.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Sphere004_8" position={[1, -1, 0]}>
                <mesh
                  name="Object_12"
                  geometry={nodes.Object_12.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Sphere005_10" position={[1, 1, 0]}>
                <mesh
                  name="Object_14"
                  geometry={nodes.Object_14.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Sphere006_12" position={[-1, 1, 0]}>
                <mesh
                  name="Object_16"
                  geometry={nodes.Object_16.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Sphere007_14" position={[-1, -1, 0]}>
                <mesh
                  name="Object_18"
                  geometry={nodes.Object_18.geometry}
                  material={materials.material}
                />
              </group>
              <group
                name="Torus_16"
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.55}
              >
                <mesh
                  name="mesh_8"
                  geometry={nodes.mesh_8.geometry}
                  material={materials.material_1}
                />
              </group>
              <group name="Sphere008_17" position={[-1.386, -0.574, 0]}>
                <mesh
                  name="Object_22"
                  geometry={nodes.Object_22.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Sphere009_19" position={[1.386, 0.574, 0]}>
                <mesh
                  name="Object_24"
                  geometry={nodes.Object_24.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Sphere010_21" position={[-0.574, 1.386, 0]}>
                <mesh
                  name="Object_26"
                  geometry={nodes.Object_26.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Sphere011_23" position={[0.574, -1.386, 0]}>
                <mesh
                  name="Object_28"
                  geometry={nodes.Object_28.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Sphere012_25" position={[1.307, -0.541, 0]}>
                <mesh
                  name="Object_30"
                  geometry={nodes.Object_30.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Sphere013_27" position={[0.541, 1.307, 0]}>
                <mesh
                  name="Object_32"
                  geometry={nodes.Object_32.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Sphere014_29" position={[-1.307, 0.541, 0]}>
                <mesh
                  name="Object_34"
                  geometry={nodes.Object_34.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Sphere015_31" position={[-0.541, -1.307, 0]}>
                <mesh
                  name="Object_36"
                  geometry={nodes.Object_36.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Sphere016_33" position={[-1.468, -0.398, 0]}>
                <mesh
                  name="Object_38"
                  geometry={nodes.Object_38.geometry}
                  material={materials.lint}
                />
              </group>
              <group name="Sphere017_35" position={[1.448, 0.391, 0]}>
                <mesh
                  name="Object_40"
                  geometry={nodes.Object_40.geometry}
                  material={materials.lint}
                />
              </group>
              <group name="Sphere018_37" position={[-0.398, 1.464, 0]}>
                <mesh
                  name="Object_42"
                  geometry={nodes.Object_42.geometry}
                  material={materials.lint}
                />
              </group>
              <group name="Sphere019_39" position={[0.394, -1.468, 0]}>
                <mesh
                  name="Object_44"
                  geometry={nodes.Object_44.geometry}
                  material={materials.lint}
                />
              </group>
              <group name="Sphere020_41" position={[1.226, -0.705, 0]}>
                <mesh
                  name="Object_46"
                  geometry={nodes.Object_46.geometry}
                  material={materials.lint}
                />
              </group>
              <group name="Sphere021_43" position={[0.712, 1.24, 0]}>
                <mesh
                  name="Object_48"
                  geometry={nodes.Object_48.geometry}
                  material={materials.lint}
                />
              </group>
              <group name="Sphere022_45" position={[-1.226, 0.705, 0]}>
                <mesh
                  name="Object_50"
                  geometry={nodes.Object_50.geometry}
                  material={materials.lint}
                />
              </group>
              <group name="Sphere023_47" position={[-0.705, -1.226, 0]}>
                <mesh
                  name="Object_52"
                  geometry={nodes.Object_52.geometry}
                  material={materials.lint}
                />
              </group>
              <group name="Sphere024_49" position={[-1.188, -0.916, 0]}>
                <mesh
                  name="Object_54"
                  geometry={nodes.Object_54.geometry}
                  material={materials.lint}
                />
              </group>
              <group name="Sphere025_51" position={[1.188, 0.916, 0]}>
                <mesh
                  name="Object_56"
                  geometry={nodes.Object_56.geometry}
                  material={materials.lint}
                />
              </group>
              <group name="Sphere026_53" position={[-0.916, 1.188, 0]}>
                <mesh
                  name="Object_58"
                  geometry={nodes.Object_58.geometry}
                  material={materials.lint}
                />
              </group>
              <group name="Sphere027_55" position={[0.916, -1.188, 0]}>
                <mesh
                  name="Object_60"
                  geometry={nodes.Object_60.geometry}
                  material={materials.lint}
                />
              </group>
              <group name="Sphere028_57" position={[1.418, -0.186, 0]}>
                <mesh
                  name="Object_62"
                  geometry={nodes.Object_62.geometry}
                  material={materials.lint}
                />
              </group>
              <group name="Sphere029_59" position={[0.182, 1.402, 0]}>
                <mesh
                  name="Object_64"
                  geometry={nodes.Object_64.geometry}
                  material={materials.lint}
                />
              </group>
              <group name="Sphere030_61" position={[-1.402, 0.182, 0]}>
                <mesh
                  name="Object_66"
                  geometry={nodes.Object_66.geometry}
                  material={materials.lint}
                />
              </group>
              <group name="Sphere031_63" position={[-0.182, -1.402, 0]}>
                <mesh
                  name="Object_68"
                  geometry={nodes.Object_68.geometry}
                  material={materials.lint}
                />
              </group>
              <group name="Torus002_65" scale={0.562}>
                <mesh
                  name="Object_70"
                  geometry={nodes.Object_70.geometry}
                  material={materials.lirin}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/the_great_morpheus.glb");
