/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/tree.glb 
Author: farhad.Guli (https://sketchfab.com/farhad.Guli)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tree-7016d1d32fe748f0a8b3f5eb39374bc4
Title: Tree
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Tree({ position, scale, props }) {
  const { nodes, materials } = useGLTF("/models/tree.glb");
  return (
    <group {...props} dispose={null} position={position} scale={scale}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.formica_cinza}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Vegetation_Bark_Maple_1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/tree.glb");
