/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/high_detailed_rex_animation.glb
Author: Al-Deezel (https://sketchfab.com/Al-dezel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/high-detailed-rex-animation-849222685ea349bd82bff8dac052998c
Title: High detailed rex animation
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { DissolveMaterial } from "../../scenes/dissolve/DissolveMaterial";

export function Trex(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/trex_animation.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["roar"].reset().fadeIn(0.5).play();
    return () => actions["roar"].fadeOut(0.5);
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.29}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="RootNode0_0" scale={0.01}>
                <group name="skeletal3_3">
                  <group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <group name="TRex2_2_correction">
                      <group name="TRex2_2" />
                    </group>
                    <skinnedMesh name="Object_80" geometry={nodes.Object_80.geometry} skeleton={nodes.Object_80.skeleton}>
                      <DissolveMaterial baseMaterial={materials.material_0} visible={props.dissolveVisible} onFadeOut={props.onFadeOut} color="#0082b2" />
                    </skinnedMesh>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/trex_animation.glb");
