/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/unstable_antimatter.glb 
Author: tamminen (https://sketchfab.com/tamminen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/unstable-antimatter-d057d7fd6d07417fb479934d2bfc1eb4
Title: Unstable Antimatter
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function UnstableAntimatter(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/unstable_antimatter.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Icosphere_0">
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials.base}
                />
              </group>
              <group name="Icosphere001_1" scale={1.09}>
                <mesh
                  name="Object_6"
                  geometry={nodes.Object_6.geometry}
                  material={materials.material}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/unstable_antimatter.glb");
