/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/valley.glb 
Author: MisterBeasley (https://sketchfab.com/MisterBeasley)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dolly-of-the-uncanny-valley-42182bad0fa64b8d9df296d724eae303
Title: Dolly of the Uncanny Valley
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Valley(props, {naught=0}) {
  const { nodes, materials } = useGLTF('/models/valley.glb')

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Band} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Bangs} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Ears} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.EyeMoisture_Genesis_8_Female_Eyelashes} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.EyeSocket} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Eyelashes} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Face} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.LeftBootBuckles} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.LeftBootMidPlate} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.LeftBootSideCloth} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.LeftBootTopPlate} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.LeftClothTop} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.LeftKneeCloth} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.LeftShinCloth} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.LeftShinPlate} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.LeftShinStraps} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Lips} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.material_39} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Ribbon} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.RightBootBuckles} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.RightBootMidPlate} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.RightBootSideCloth} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.RightBootTopPlate} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.RightClothTop} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.RightKneeCloth} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.RightShinCloth} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.RightShinPlate} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.RightShinStraps} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.Skirt1} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Arms} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Arms} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.Elastic} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.EyeMoisture} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.Fingernails} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.Head} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.Head} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Heels} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.Irises} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Cornea} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.Lace1} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.Lace1} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.Lace2} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.LeftAnkleCover} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.LeftAnkleCover} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.LeftBootLowerPlate} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.LeftBootRings} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.LeftBootRings} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.LeftBootStraps} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.LeftBootStraps} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.LeftBootStuds} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.LeftFootCover} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.LeftFootCover} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.LeftHeelCover} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.LeftHeelCover} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.LeftSole} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.LeftSole} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.LeftThighCloth} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.LeftThighCloth} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.Legs} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.Legs} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.Mouth} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.PiggyTails} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.PiggyTails} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.PiggyTails} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.Pupils} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.RightAnkleCover} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.RightAnkleCover} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.RightBootLowerPlate} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.RightBootRings} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.RightBootRings} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.RightBootStraps} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.RightBootStraps} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.RightBootStuds} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.RightFootCover} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.RightFootCover} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.RightHeelCover} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.RightHeelCover} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.RightSole} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.RightSole} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.RightThighCloth} />
        <mesh geometry={nodes.Object_84.geometry} material={materials.RightThighCloth} />
        <mesh geometry={nodes.Object_85.geometry} material={materials.Sclera} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.Skirt2} scale={naught}/>
        <mesh geometry={nodes.Object_87.geometry} material={materials.Skirt2} />
        <mesh geometry={nodes.Object_88.geometry} material={materials.Skirt3} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.Skirt4} />
        <mesh geometry={nodes.Object_90.geometry} material={materials.SkirtFrill} />
        <mesh geometry={nodes.Object_91.geometry} material={materials.Sole} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.SoleTop} />
        <mesh geometry={nodes.Object_93.geometry} material={materials.Strands} />
        <mesh geometry={nodes.Object_94.geometry} material={materials.Strap} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.Teeth} />
        <mesh geometry={nodes.Object_96.geometry} material={materials.Toenails} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.material_74} scale={naught} />
        <mesh geometry={nodes.Object_98.geometry} material={materials.material_74} scale={naught} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.material_74} scale={naught} />
        <mesh geometry={nodes.Object_100.geometry} material={materials.Torso} />
        <mesh geometry={nodes.Object_101.geometry} material={materials.Torso} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/valley.glb')
