/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/victorian_couch.glb 
Author: kbangart (https://sketchfab.com/kbangart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/victorian-couch-6446946d72e34074bf188c78e57ccadd
Title: Victorian Couch
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function VictorianCouch(props) {
  const { nodes, materials } = useGLTF('/models/victorian_couch.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Merged_Cushion} position={[0, 0.729, 0.749]} />
    </group>
  )
}

useGLTF.preload('/models/victorian_couch.glb')
