/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/warp_tunnel.glb 
Author: Miguelangelo Rosario (https://sketchfab.com/miguelangelo2k)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/warp-tunnel-remix-2021-968fcd70846e4829a9e34af888e47e1f
Title: Warp Tunnel - Remix 2021
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function WarpTunnel(props) {
  const { nodes, materials } = useGLTF("/models/warp_tunnel.glb");
  const tunnel = useRef();
  useFrame(() => {
    tunnel.current.rotation.x += 0.0005;
  });
  return (
    <group
      
      {...props}
      dispose={null}
      position={[-24, -136, 19]}
      scale={1}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group position={[123.93, -252.414, 0]} rotation={[0.873, 0, 0]}>
            <mesh ref={tunnel} 
              geometry={nodes["Torus001_03_-_Default_0"].geometry}
              material={materials["03_-_Default"]}
              rotation={[0, -Math.PI / 2, 0]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/warp_tunnel.glb");
